<a href="https://colab.research.google.com/github/emily-wilson/cs229-final-proj/blob/main/cs229_prediction_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

In [ ]:
!pip install librosa
!pip install -U -q transformers
!pip install torch
!pip install evaluate
!pip install jiwer ## evaluate dependency

Requirement already satisfied: librosa in /usr/local/lib/python3.12/dist-packages (0.11.0)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.12/dist-packages (from librosa) (3.1.0)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.60.0)
Requirement already satisfied: numpy>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from librosa) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.16.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.5.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.4.2)
Requirement already satisfied: soundfile>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.13.1)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.0.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.15.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.4)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from lazy_loader>=0.1->librosa) (25.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51.0->librosa) (0.43.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa) (4.5.0)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa) (2.32.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile>=0.12.1->librosa) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.23)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2025.11.12)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 137.7 MB/s eta 0:00:00
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.9.0+cu126)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.0 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6
Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.3.1)
Collecting rapidfuzz>=3.9.7 (from jiwer)
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 37.7 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, jiwer
Successfully installed jiwer-4.0.0 rapidfuzz-3.14.3

In [ ]:
#@title Imports
import librosa
import numpy as np
import json
from tqdm.notebook import trange
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC, AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline, WhisperTokenizer, WhisperFeatureExtractor
from datasets import load_dataset
import torch
import math

In [ ]:
## Set up HuggingFace to cache to GoogleDrive (from my Spr2025 CS224S HW4)
# You need to run this code for every colab runtime
from google.colab import drive
import os

drive.mount('/content/drive')

# creating a folder for saving the cache
drive_cache_dir = "/content/drive/MyDrive/hf_datasets_cache"
os.makedirs(drive_cache_dir, exist_ok=True)

# changing hf cache directory
os.environ["HF_DATASETS_CACHE"] = drive_cache_dir
os.environ["HF_HOME"] = drive_cache_dir

Mounted at /content/drive

In [ ]:
MODEL_ID = "openai/whisper-large-v3"

## Set up Google Drive dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
APROCSA_DATASET_LOC = "cs229_final_proj/aprocsa_dataset"
dataset_filename = f'drive/MyDrive/{APROCSA_DATASET_LOC}/dataset.json'

# Using Whisper model for prediction and pretraining

In [ ]:
#@title Load dataset
dataset = load_dataset("json", data_files=dataset_filename, field="dataset", split="train")

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
MAX_LEN = 15 * 16000
def filter_dataset(audio):
  return len(audio["array"]) <= MAX_LEN

dataset = dataset.filter(filter_dataset, include_columns=["audio"])

In [ ]:
#@title Baseline prediction with Whispr model
## Code is based on model card for Whispr on HuggingFace (https://huggingface.co/openai/whisper-large-v3)
device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model = AutoModelForSpeechSeq2Seq.from_pretrained(
    MODEL_ID, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
)
model.to(device)

processor = AutoProcessor.from_pretrained(MODEL_ID)

pipe = pipeline(
    "automatic-speech-recognition",
    model=model,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    torch_dtype=torch_dtype,
    device=device,
)

results = []
for result in pipe(dataset, batch_size=2, generate_kwargs={"language": "english"}):
  results.append(result)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

generation_config.json: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/340 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

normalizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!
Device set to use cuda:0

TypeError: We expect a numpy ndarray or torch tensor as input, got `<class 'datasets.arrow_dataset.Dataset'>`

In [ ]:
from jiwer import wer, cer
wers = []
cers = []
for i in range(len(results)):
  reference = test_data[i]["transcript"]["transcript"].lower()
  hypothesis = clean_output(results[i]["text"])

  wers.append(wer(reference, hypothesis))
  cers.append(cer(reference, hypothesis))

wers = np.array(wers)
cers = np.array(cers)

print("Average WER: ", np.mean(wers))
print("Average CER: ", np.mean(cers))

In [ ]:
import pandas as pd
output_csv_path = "drive/MyDrive/cs229_final_proj/baseline_whisper_preds.csv"

In [ ]:
#@title Write results to CSV
data = {
    "hypothesis": [result["text"] for result in results],
    "reference": [d["transcript"]["transcript"] for d in test_data],
    "wer": wers,
    "cer": cers
}

df = pd.DataFrame(data)
df.to_csv(output_csv_path, index=False)

In [ ]:
#@title Loading data from csv
df = pd.read_csv(output_csv_path)

In [ ]:
#@title Reformat csv
from jiwer import wer, cer, mer

hypotheses = df["hypothesis"]
references = df["reference"]

hypotheses = [h.lower() for h in hypotheses]
references = [r.lower() for r in references]

wers = [wer(references[i], hypotheses[i]) for i in range(len(hypotheses))]
cers = [cer(references[i], hypotheses[i]) for i in range(len(hypotheses))]
mers = [mer(references[i], hypotheses[i]) for i in range(len(hypotheses))]

print("Average WER: ", np.mean(np.array(wers)))
print("Average CER: ", np.mean(np.array(cers)))
print("Average MER: ", np.mean(np.array(mers)))

data = {
    "hypothesis": hypotheses,
    "reference": references,
    "wer": wers,
    "cer": cers,
    "mer": mers,
}
df = pd.DataFrame(data)

In [ ]:
df.to_csv(output_csv_path, index=False)

In [ ]:
from google.colab import data_table
data_table.enable_dataframe_formatter()
df

In [ ]:
wer_cer_diff = [abs(wers[i] - cers[i]) for i in range(len(wers))]
diff_data = {
    "hypothesis": [result["text"].strip() for result in results],
    "reference": [d["transcript"]["transcript"] for d in test_data],
    "wer": wers,
    "cer": cers,
    "diff": wer_cer_diff
}

df2 = pd.DataFrame(diff_data)
df2

# Model improvements for Whisper ASR

The code here is based on the HuggingFace blog post for how to finetune the Whisper model

In [ ]:
#@title Set up Weights and Biases for finetuning logging
# (from Weights and Biases blog post https://wandb.ai/ayush-thakur/huggingface/reports/How-To-Fine-Tune-Hugging-Face-Transformers-on-a-Custom-Dataset--Vmlldzo0MzQ2MDc)
# Install Weights and Biases
!pip install wandb -q

# Import wandb
import wandb

# Login with your authentication key
wandb.login()

# setup wandb environment variables
%env WANDB_ENTITY=emilywilson6263/emilywilson6263-stanford-university
%env WANDB_PROJECT=cs-229-final-project

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:

KeyboardInterrupt:

In [ ]:
#@title Prepare feature extractor
from transformers import WhisperFeatureExtractor

feature_extractor = WhisperFeatureExtractor.from_pretrained(MODEL_ID)

In [ ]:
#@title Load dataset

dataset = load_dataset("json", data_files=dataset_filename, field="dataset", split="train")

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
#@title Remove special characters that will be added back in post-processing
import re

encodings_to_remove = [r"\[\+ gram\]", "\[/\]", "&=shrugs", "\[//\]", "&\-", "&\+", "\[\+ exc\]", "\+<", "\[\+ jar\]"]
def remove_some_special_characters(batch):
  transcript = re.sub(r"[<>]", "", batch["transcript"]["transcript"])
  for encoding in encodings_to_remove:
    transcript = re.sub(encoding, "", transcript)
  batch["transcript"] = transcript
  return batch

dataset = dataset.map(remove_some_special_characters)

<>:4: SyntaxWarning: invalid escape sequence '\['
<>:4: SyntaxWarning: invalid escape sequence '\['
<>:4: SyntaxWarning: invalid escape sequence '\-'
<>:4: SyntaxWarning: invalid escape sequence '\+'
<>:4: SyntaxWarning: invalid escape sequence '\['
<>:4: SyntaxWarning: invalid escape sequence '\+'
<>:4: SyntaxWarning: invalid escape sequence '\['
<>:4: SyntaxWarning: invalid escape sequence '\['
<>:4: SyntaxWarning: invalid escape sequence '\['
<>:4: SyntaxWarning: invalid escape sequence '\-'
<>:4: SyntaxWarning: invalid escape sequence '\+'
<>:4: SyntaxWarning: invalid escape sequence '\['
<>:4: SyntaxWarning: invalid escape sequence '\+'
<>:4: SyntaxWarning: invalid escape sequence '\['
/tmp/ipython-input-3113689591.py:4: SyntaxWarning: invalid escape sequence '\['
  encodings_to_remove = [r"\[\+ gram\]", "\[/\]", "&=shrugs", "\[//\]", "&\-", "&\+", "\[\+ exc\]", "\+<", "\[\+ jar\]"]
/tmp/ipython-input-3113689591.py:4: SyntaxWarning: invalid escape sequence '\['
  encodings_to_remove = [r"\[\+ gram\]", "\[/\]", "&=shrugs", "\[//\]", "&\-", "&\+", "\[\+ exc\]", "\+<", "\[\+ jar\]"]
/tmp/ipython-input-3113689591.py:4: SyntaxWarning: invalid escape sequence '\-'
  encodings_to_remove = [r"\[\+ gram\]", "\[/\]", "&=shrugs", "\[//\]", "&\-", "&\+", "\[\+ exc\]", "\+<", "\[\+ jar\]"]
/tmp/ipython-input-3113689591.py:4: SyntaxWarning: invalid escape sequence '\+'
  encodings_to_remove = [r"\[\+ gram\]", "\[/\]", "&=shrugs", "\[//\]", "&\-", "&\+", "\[\+ exc\]", "\+<", "\[\+ jar\]"]
/tmp/ipython-input-3113689591.py:4: SyntaxWarning: invalid escape sequence '\['
  encodings_to_remove = [r"\[\+ gram\]", "\[/\]", "&=shrugs", "\[//\]", "&\-", "&\+", "\[\+ exc\]", "\+<", "\[\+ jar\]"]
/tmp/ipython-input-3113689591.py:4: SyntaxWarning: invalid escape sequence '\+'
  encodings_to_remove = [r"\[\+ gram\]", "\[/\]", "&=shrugs", "\[//\]", "&\-", "&\+", "\[\+ exc\]", "\+<", "\[\+ jar\]"]
/tmp/ipython-input-3113689591.py:4: SyntaxWarning: invalid escape sequence '\['
  encodings_to_remove = [r"\[\+ gram\]", "\[/\]", "&=shrugs", "\[//\]", "&\-", "&\+", "\[\+ exc\]", "\+<", "\[\+ jar\]"]

Map:   0%|          | 0/1645 [00:00<?, ? examples/s]

In [ ]:
#@title Build string replacement map
LONG_PAUSE_STRING = r"\(...\)"
LONG_PAUSE_TOKEN = "<long_pause>"
SHORT_PAUSE_STRING = r"\(.\)"
SHORT_PAUSE_TOKEN = "<short_pause>"
MEDIUM_PAUSE_STRING = r"\(..\)"
MEDIUM_PAUSE_TOKEN = "<medium_pause>"
GES_STRING = r"&ges=\w+\s"
GES_TOKEN = "<gesture>"
UNK_TOKEN = "xxx"
COMMENT_TOKEN = r"\[% \w+\]"
COMMENT_REPLACE = ""
TRAIL_OFF_STRING = r"\+..."
TRAIL_OFF_QUESTION_STRING = r"\+..?"
TRAIL_OFF_TOKEN = "<trail_off>"
LAUGHTER_STRING = "&=laughs"
LAUGHTER_TOKEN = "<laughter>"

STRING_REPLACEMENT_MAP = {
    LONG_PAUSE_STRING: LONG_PAUSE_TOKEN,
    MEDIUM_PAUSE_STRING: MEDIUM_PAUSE_TOKEN,
    SHORT_PAUSE_STRING: SHORT_PAUSE_TOKEN,
    GES_STRING: GES_TOKEN,
    COMMENT_TOKEN: COMMENT_REPLACE,
    TRAIL_OFF_STRING: TRAIL_OFF_TOKEN,
    LAUGHTER_STRING: LAUGHTER_TOKEN,
    TRAIL_OFF_QUESTION_STRING: TRAIL_OFF_TOKEN,
}

In [ ]:
#@title Reformat special characters
def reformat_chat_transcription_annotations(batch):
  for string, replace in STRING_REPLACEMENT_MAP.items():
    batch["transcript"] = re.sub(string, replace, batch["transcript"])

dataset = dataset.map(reformat_chat_transcription_annotations)

Map:   0%|          | 0/1622 [00:00<?, ? examples/s]

NameError: name 're' is not defined

In [ ]:
#@title Prepare the tokenizer for the special characters in the CHAT file format
from transformers import WhisperTokenizer

tokenizer = WhisperTokenizer.from_pretrained(MODEL_ID)

special_tokens_dict = {}
special_tokens_list = list(STRING_REPLACEMENT_MAP.values())
for i in range(len(special_tokens_list)):
  special_tokens_dict[len(tokenizer) + i] = special_tokens_list[i]

tokenizer.add_tokens(list(special_tokens_dict.values()))

In [ ]:
print(tokenizer.vocab_size)

In [ ]:
## Only need to run this once
!curl -O f "drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/aprocsa_dataset/merges.txt" https://huggingface.co/openai/whisper-large/resolve/main/merges.txt

In [ ]:
#@title Set up processor
from transformers import WhisperProcessor

processor = WhisperProcessor(feature_extractor, tokenizer)

## Prepare dataset

In [ ]:
MAX_LEN = 15*16000
def filter_dataset(audio):
  return len(audio["array"]) <= MAX_LEN

def prepare_dataset(batch):
    audio = batch["audio"]["array"]
    ## Audio was resampled in dataset creation so it is sampled at 16kHz
    batch["audio"] = audio

    # compute log-Mel input features from input audio array
    batch["input_features"] = feature_extractor(batch["audio"], sampling_rate=16000).input_features[0]

    # encode target text to label ids
    # with processor.as_target_processor():
    batch["labels"] = tokenizer(batch["transcript"]).input_ids
    return batch

In [ ]:
dataset = dataset.filter(filter_dataset, input_columns=["audio"])
dataset = dataset.map(prepare_dataset, num_proc=1)

splits = dataset.train_test_split(test_size=0.1)
train_data = splits["train"]
test_data = splits["test"]

splits = train_data.train_test_split(test_size=0.2)
train_data = splits["train"]
valid_data = splits["test"]

Filter:   0%|          | 0/1622 [00:00<?, ? examples/s]

Map:   0%|          | 0/1622 [00:00<?, ? examples/s]

NameError: name 'tokenizer' is not defined

In [ ]:
#@title Set up model checkpoint using whisper-large-v3
from transformers import WhisperForConditionalGeneration

model = WhisperForConditionalGeneration.from_pretrained(MODEL_ID)

In [ ]:
model.resize_token_embeddings(len(tokenizer))

In [ ]:
# model.config.vocab_size = len(all_tokens)
model.config.forced_decoder_ids = None

In [ ]:
#@title Set up data collator
## Note this comes directly from the HuggingFace blog post of how to fine-tune Whisper
import torch

from dataclasses import dataclass
from typing import Any, Dict, List, Union

@dataclass
class DataCollator:
  processor: Any
  decoder_start_token_id: int

  def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
    # split inputs and labels since they have to be of different lengths and need different padding methods
    # first treat the audio inputs by simply returning torch tensors
    input_features = [{"input_features": feature["input_features"]} for feature in features]
    batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")

    # get the tokenized label sequences
    label_features = [{"input_ids": feature["labels"]} for feature in features]
    # pad the labels to max length
    labels_batch = self.processor.tokenizer.pad(label_features, return_tensors="pt")

    # replace padding with -100 to ignore loss correctly
    labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)

    # if bos token is appended in previous tokenization step,
    # cut bos token here as it's append later anyways
    if (labels[:, 0] == self.decoder_start_token_id).all().cpu().item():
        labels = labels[:, 1:]

    batch["labels"] = labels

    return batch

In [ ]:
data_collator = DataCollator(
  processor=processor,
  decoder_start_token_id=model.config.decoder_start_token_id,
)

In [ ]:
#@title Define metrics
## We are using CER (character error rate) here since we are fine-tuning the model
## to predict the special characters of the CHAT transcript
import evaluate

metric = evaluate.load("cer")

## Also copied from HuggingFace blog post
def compute_metrics(pred):
  pred_ids = pred.predictions
  label_ids = pred.label_ids

  ## TODO: should we do this? for us sometimes gaps may have semantic meaning
  # replace -100 with the pad_token_id
  label_ids[label_ids == -100] = tokenizer.pad_token_id

  # we do not want to group tokens when computing the metrics
  pred_str = tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
  label_str = tokenizer.batch_decode(label_ids, skip_special_tokens=True)

  cer = 100 * metric.compute(predictions=pred_str, references=label_str)

  return {"cer": cer}

In [ ]:
#@title Set up training args and trainer
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer, logging

output_dir = f'drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/finetuning/'

training_args = Seq2SeqTrainingArguments(
    output_dir=output_dir,  # change to a repo name of your choice
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,  # increase by 2x for every 2x decrease in batch size
    learning_rate=1e-5,
    warmup_steps=50,
    max_steps=1600,
    fp16=True,
    eval_strategy="steps",
    per_device_eval_batch_size=8,
    predict_with_generate=True,
    generation_max_length=280,
    save_steps=400,
    eval_steps=400,
    logging_steps=10,
    report_to=None,
    load_best_model_at_end=True,
    metric_for_best_model="cer",
    greater_is_better=False,
    push_to_hub=False,
    disable_tqdm=False,
    torch_empty_cache_steps=5
)

trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=train_data,
    eval_dataset=valid_data,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    tokenizer=processor.tokenizer,
)

logging.enable_progress_bar()
logging.set_verbosity_info()

In [ ]:
!rm ~/.netrc
!wandb login

In [ ]:
torch.cuda.empty_cache()

In [ ]:
#@title Start training!
import os

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

torch.cuda.empty_cache()

trainer.train()

## Evaluate model

### Load and prepare dataset

In [ ]:
dataset = load_dataset("json", data_files=dataset_filename, field="dataset", split="train")

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
MAX_LEN = 15*16000
def filter_dataset(audio):
  return len(audio["array"]) <= MAX_LEN

def process_dataset_for_evaluation(batch):
  batch["audio"] = batch["audio"]["array"]
  return batch

In [ ]:
dataset = dataset.filter(filter_dataset, input_columns=["audio"])
dataset = dataset.map(process_dataset_for_evaluation)

splits = dataset.train_test_split(test_size=0.1)
train_data = splits["train"]
test_data = splits["test"]

splits = train_data.train_test_split(test_size=0.2)
train_data = splits["train"]
valid_data = splits["test"]

Filter:   0%|          | 0/1645 [00:00<?, ? examples/s]

Map:   0%|          | 0/1622 [00:00<?, ? examples/s]

In [ ]:
model_checkpoint = "drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/finetuning/checkpoint-1200"

## Predict

In [ ]:
## Code is based on model card for Whispr on HuggingFace (https://huggingface.co/openai/whisper-large-v3)
## TODO: run this on the test dataset first to get a baseline
from transformers import WhisperForConditionalGeneration

device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model = WhisperForConditionalGeneration.from_pretrained(model_checkpoint)
model.to(device)

tokenizer = WhisperTokenizer.from_pretrained(model_checkpoint)
feature_extractor = WhisperFeatureExtractor.from_pretrained(MODEL_ID)

results = []
references = []
for batch in valid_data.batch(batch_size=4):
  audio_arrays = batch["audio"]
  features = feature_extractor(audio_arrays, sampling_rate=16000, return_tensors="pt").input_features.to(device)
  with torch.no_grad():
    prediction_ids = model.generate(inputs=features)
  predictions = tokenizer.batch_decode(prediction_ids, skip_special_tokens=True)
  results.extend(predictions)
  references.extend(batch["transcript"])

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/340 [00:00<?, ?B/s]

Batching examples:   0%|          | 0/292 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/models/whisper/generation_whisper.py:655: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
Using custom `forced_decoder_ids` from the (generation) config. This is deprecated in favor of the `task` and `language` flags/config options.
Transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English. This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`. See https://github.com/huggingface/transformers/pull/28687 for more details.
`generation_config` default values have been modified to match model-specific defaults: {'suppress_tokens': [1, 2, 7, 8, 9, 10, 14, 25, 26, 27, 28, 29, 31, 58, 59, 60, 61, 62, 63, 90, 91, 92, 93, 359, 503, 522, 542, 873, 893, 902, 918, 922, 931, 1350, 1853, 1982, 2460, 2627, 3246, 3253, 3268, 3536, 3846, 3961, 4183, 4667, 6585, 6647, 7273, 9061, 9383, 10428, 10929, 11938, 12033, 12331, 12562, 13793, 14157, 14635, 15265, 15618, 16553, 16604, 18362, 18956, 20075, 21675, 22520, 26130, 26161, 26435, 28279, 29464, 31650, 32302, 32470, 36865, 42863, 47425, 49870, 50254, 50258, 50359, 50360, 50361, 50362, 50363], 'begin_suppress_tokens': [220, 50257]}. If this is not desired, please set these values explicitly.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.

In [ ]:
#@title Replace training tokens with CHAT format characters
import re

for i in range(len(results)):
  for key, value in STRING_REPLACEMENT_MAP.items():
    if value != "" and re.match(value, results[i]):
      results[i] = re.sub(value, key, results[i])
print(results)

[' mhm .', ' alright .', ' டே hello .', ' mhm .', ' Yep .', " I don't have a  uh uh um maid to run this house .", ' So ‡ okay .', " look at everything's that's happening .", " I don't know why .", ' close . ', ' . ', ' Beraia.', ' The universe knows sometimes .', " I don't know .", ' yeah ‡ drunk . ', ' take a little bit of time to look at those pictures .', ' I samo kao da ste ube, počekajte učištajne uči koje se može, sato really wanna hear your language .', ' Og så lever hun op i atticen .', ' okay .', ' they  they tried to uh get  stick it in their feet to the slipper .', ' But a lot.)ha.) s changed .', ' and that was it .', " That's uh very current and uh uh very important at the moment .", " I don't know why .", ' Ok.', " I'm just  I can't imagine having to face a bill like that and having the uncertainty of how much would be covered .", " uh I  I don't know .", ' So you do those ?', ' hm mhm .', ' Mhm .', ' okay .', " but it's good &-ges .", ' and Cinderella came .', ' The um young boy is  uh has no u umbrella from the mother .', ' I  do &//laughs okay ‡ I do ...', ' okay .', ' okay .', ' So um the  mo the mother had left a dress for her .', ' Mhm .', ' stories . ', ' and  and uh um.).) I will be al able to spell it .', 'hm.).) .', ' yeah mhm .', ' okay .', ' دی سی  the bed is in the  .', ' Mhm  mhm .', ' um um the  um the call went out that the prince was looking for someone to fit in the slipper .', ' and  and the spoon is on the uh bread .', ' and he looked out the window to see who k had kicked it .', ' وپن دن  th Cinderella came down and say .', ' the one here . ', ' Så jeg har hafta  harta work on that .', ' Tõeva .', ' you say them or you &..?', " Then I'll put the book away and have you tell me the story of Cinderella in your own words .", ' um tell me about what you see .', ' I was alone in my small house .', ' Gotcha .', ' and you put it together .', ' Og uh &//laughs og Cinderella er små .', ' every time . ', ' oh cats ! ', ' uh so I  w I could.).) do my hand and s stuff .', ' Mhm .', ' If that makes sense .', ' og nu walker vi til . ', ' so  .', ' mhm .', ' um well ‡ um I woke up and um um sit up .', ' what have you done to try and get better ?', ' But uh the insurance cut  cut me off .', " No, no ‡ it's fine  it's fine .", " I'll think about it .", " and she ri tried to get the cat down , but he wouldn't go .", ' نم .', ' بمشه .', ' and uh I draw .', ' uh just &//ges uh five you-know four  four words over and over again . ', ' In um um she gave .', ' Again and again I watched it , the whole damn thing for  for  m b um for a &&$laughs .', ' Um have you had any therapies after your stroke ?', ' Okay .', " but I just  you know I just can't .", ' and Cinderella had the uh uh scrub the floors .', ' Yep .', ' Mhm .', ' So ‡ that definitely family .', ' just uh totally at random ? ', " but Ben doesn't understand yet .", ' and it struck midnight .', ' I joined it then .', ' tell me how you would make a peanut butter and jelly sandwich .', ' um  um I have trouble with uh and  and the  and     all that .', ' Mhm .', ' It was a joy to do that .', " but uh I don't know .", ' and I had a deep depression .', " I'm  I'm for  s I'm seventy one .", ' All right .', ' No .', ' Your mic fell .', ' And then I said it .', ' you know .', ' Yeah &//laughs .', ' Month .', ' youknow like uh the ribbons and stuff like that .', ' mhm . ', ' um it could be happy or sad .', ' yeah  to read it  al aloud you-know .', ' Simple words are okay or are still hard ?', ' um &//laughs um but only um she had one um slipper , a gold slipper .', ' yeah .', ' okay .', ' OK . ', ' So how would you make it ?', ' Mhm .', ' But uh I .).) I  I  w I wanted to  when l released me I  I wanted to drive &//laughs . ', ' Yeah .', " uh we'd all been dead you-know &//laughs .", ' really &//points . ', ' Oh bobsledding ?', ' really weird &//ges . ', ' So ‡ what about your recovery ?', ' I know that you get it a lot sooner than when I finish saying it .', " Yeah ‡ it's a lot of life adjustments „ I'm sure .", ' yeah ‡ better than if it was the first one you had „ yeah .', ' Så han tar opp omvendet og går til skole .', ' uh they tell a story .', ' and he lost his ladder .', ' So ‡ the last part for this bit ,', ' I want to say it .', ' but it sounds like they all were helping you a lot ?', " So um again here's  the these are some more pictures that tell a story .", ' uh I can do it while driving you-know .', ' So he  uh he goes out in the rain .', " Saya didn't  m I didn't mention the bird is just sitting there looking .", ' uh twenty t.) one .', ' or he gonna discipline him . ', ' ladder   .  ', ' So now um tell me as much about the story of Cinderella as you can .', ' Yeah  yeah .', " But uh &//laughs just like uh if I was going to Lowe's and I'd talk to the uh person you know .", ' And  s but I  uh.).) uh if I had .).) um.).) look it up in dictionary or um &//ges.) it .).) light &q will go off . ', ' and to be as far as  to come as far as you have .', ' I remember um we always kiss before we uh go to bed .', " when you're ready .", ' O okay .', ' &-go &-mhm .', ' Take this uh umbrella because it looks like rain .', ' .', ' .', " Okay ‡ so ‡ I'm gonna ask you just a couple more things where we'll be talking .", ' And so they all went to the ball .', ' I can  mhm .', ' but somebody s other  b other people had joined  just joined or has had j more than other people .', " Eh it's good .", " I don't think so &//laughs .", " but I don't like it now „ you-know .", ' treadmill all the time . ', " So now I'm gonna ask you to do a few more things where you need to talk .", ' yeah but  .', ' so .', ' so uh I just  uh I decided not go along li those lines .', ' The end .', ' end  end .  ', ' evening . ', " Let's see .", ' It looks like they tried that once &//laughs .', ' How do the siblings feel about having more kids ?', ' Okay .', " and say I will  I will use this  this my mother's dress .", " didn't  .", ' I like your distinction between the knife for the peanut butter and the spoon for the jelly .', ' Okay .', " yeah but it's good .", ' Okay .', ' and mama said it uh you need a  umbrella .', " That's  that's my take on it .", ' and  and  and the dog is uh barking for uh the man .', 'કયા કા કા  ', ' Yes .', ' مhm .', ' Go on .', ' um I r like to read .', ' Yeah .', " Well ‡ I've got the whole picture book here &//laughs for you to uh go ahead and flip through .", " I can't um.).) probably that  get the words out .", ' but faith &//ges . ', ' So if you could tell me a story again with a beginning , middle and end about these pictures .', ' so  .', ' and uh um the General Motors stopped that uh retirement in probably oa o seven or o eight .', ' Okay . ', ' mhm .', ' It can be happy .', ' mhm .', " That's a long time though .", ' Interesting.', " And so  and uh the  the clock was  was chiming twelve o'clock so that uh she gotta  gotta let go .", " It's dropping next to uh um a young  an older man who n uh grabs the plug and lets out to the window .", ' Okay .', ' You can go ahead and look through all the pictures of the story .', " Wow that's good .", ' okay .', ' و  وی مید ? ', ' yeah .', ' Yay !', ' a month . ', ' two weeks coma . ', " There's a lot going on .", ' Okay .', ' So what kinds of things do you work on in speech ?', ' and then tell me again a story about you  s what you see with a beginning , middle and end if you can .', ' gotcha .', " and um.).) it didn't feel strange or anything .", ' mhm .', ' And  um and she was riding on her  p her tricycle .', " but  z she can  that's all he was gonna do .", ' Okay .', ' drunk . ', ' Now tell me as much of the story of Cinderella as you can .', ' I mean the  the jelly .', ' they say &//laughs .', ' Mhm .', ' Have you heard of Seth Meyers ?', ' best friends with it or not ?', ' What about your first memories after the stroke ?', ' .', ' . ', " So ‡ I know you're tellin us a little bit earlier , but I didn't get to hear most of it .", " so ‡ that's why I always offer .", ' and it can be from when you were little or it can be more recently .', ' Eh mhm .', ' and taking &//ges . ', ' Have you ever heard the story of Cinderella ?', " and then I'll ask you to tell me a story with a beginning , middle , and end .", ' And  uh and  uh and I get out in July uh thirty first um of seventy three .', ' and the pumpkin uh turned out  turned back in and  and the horses uh and the men .', " Other than that I  I'd say I'm  um fairly okay „ you know .", ' &//laughs and  uh uh &//points and I  I remember.).) that  uh.).) the ride up.).) to the uh gas station uh for the e-r.).) Tenova .', ' So again just have a look all around &/.', ' väl . ', ' I want you tell me how you would make a peanut butter and jelly sandwich .', ' were . ', " I haven't been there for awhile .", ' Yeah ‡ &//laughs you were very thorough &//laughs .', ' Have you tried books on tape ?', " It's really really interesting .", ' faith . ', ' So ‡ outside of exercising , are there any other changes in your day-to-day life ?', " and the cat's up on the tree .", ' Okay ‡ um do you remember when you had your stroke ?', ' okay .', " really I don't know why .", ' you going to the ball . ', 'য়েটা થে  that was you-know the  got the ambulance and everything . ', ' yeah . ', ' Amra koh . ', ' واہ !', " and she didn't want uh Cinderella to have pretty clothes .", ' And then by this time they had grown up .', ' And then uh the  the uh the fairy godmother .', ' and  and eat it . ', ' um could you tell me about it ?', ' Yeah  yeah .', " But um so again just go ahead and look at everything that's happening in this picture .", ' så nu um &//ges . ', " I don't know .", ' too .', ' With the  with the writing ?', ' Can I get you anything ?', " but I don't drive that much &//laughs .", " It's very mother knows best &&laughs .", ' Okay .', ' Do you know Media and Palos &Verdes right near Long  uh Redondova ?', ' and um it was time to leave .', ' How do you think your speech is these days ?', ' and get a spoon .', ' okay .', ' um he says goodbye .', ' And so your family came ?', " and I didn't understand why I fell .", ' okay .', ' mhm .', ' Mhm .', ' No.', " I um I think it's a...", ' uh b uh b really interesting . ', ' and the  the  the uh lamp f fell over and stuff .', ' What can you do ?', " I don't know .", ' mhm .', ' okay .']

In [ ]:
import csv

with open('drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/transcription_results_aprocsa.csv', 'w', newline='\n') as csvfile:
  writer = csv.DictWriter(csvfile, fieldnames=["hypothesis", "reference"])

  writer.writeheader()
  for i in range(len(results)):
    writer.writerow({"hypothesis": results[i], "reference": references[i]["transcript"]})

## Post-processing predicted text

Use OpenAI to take predicted transcripts and format them to reintroduce CHAT transcription format tokens like repetitions, fragments, retracing, and filler words.

In [ ]:
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.8.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)

In [ ]:
FILLER_WORD_PREFIX = "&-"
FRAGMENT_PREFIX = "&+"
JARGON_POSTFIX = "[+ jar]"
REPETITION_PREFIX = "[/]"
RETRACING_PREFIX = "[//]"

In [ ]:
from openai import OpenAI
from google.colab import userdata

os.environ["OPENAI_API_KEY"] = userdata.get('229-open-ai-api-key')

client = OpenAI()

FILLER_WORDS_INSTRUCTIONS = f'Reformat the given string to add the prefix {FILLER_WORD_PREFIX} to all common filler words (e.g. "um", "er"). Return ONLY the reformatted string and change nothing else besides adding the prefix'

for i in range(len(results)):
  response = client.responses.create(
      model="gpt-5.1",
      instructions=FILLER_WORDS_INSTRUCTIONS,
      input=results[i]
  )

  print(response.output_text)


REPETITION_WORDS_INSTRUCTIONS = f'Reformat the given string to add the token {REPETITION_PREFIX} before any repeated words or sounds. For example the string "b b ball" should be formatted to "[/] b [/] b [/] ball'
for i in range(len(results)):
  response = client.responses.create(
      model="gpt-5.1",
      instructions=REPETITION_WORDS_INSTRUCTIONS,
      input=results[i]
  )

  print(response.output_text)

SecretNotFoundError: Secret 229-open-ai-api-key does not exist.

## Compute metrics

In [ ]:
import csv

reference = []
hypothesis = []
with open('drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/transcription_results_aprocsa.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        reference.append(row["reference"])
        hypothesis.append(row["hypothesis"])

In [ ]:
from jiwer import wer, cer
wers = []
cers = []
for i in range(len(hypothesis)):
  wers.append(wer(reference[i], hypothesis[i]))
  cers.append(cer(reference[i], hypothesis[i]))

wers = np.array(wers)
cers = np.array(cers)

print("Average WER: ", np.mean(wers))
print("Average CER: ", np.mean(cers))

Average WER:  0.38583618995741886
Average CER:  0.27915500552364264

In [ ]:
import pandas as pd
output_csv_path = "drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/finetuned_whisper_metrics.csv"

In [ ]:
#@title Write results to CSV
data = {
    "hypothesis": hypothesis,
    "reference": reference,
    "wer": wers,
    "cer": cers
}

df = pd.DataFrame(data)
df.to_csv(output_csv_path, index=False)

In [ ]:
from google.colab import data_table
data_table.enable_dataframe_formatter()
df

,hypothesis,reference,wer,cer
0,mhm .,mhm .,0.000000,0.000000
1,alright .,alright .,0.000000,0.000000
2,டே hello .,"+"" hey ‡ hello .",0.600000,0.500000
3,mhm .,mhm . [+ exc],0.500000,0.615385
4,Yep .,yep .,0.500000,0.200000
...,...,...,...,...
287,and the the the uh lamp f fell over and stu...,&=laughs and the [/] the [/] the &-uh lamp &+f...,0.333333,0.279412
288,What can you do ?,and &-um (..) &-um (.) what can you do ?,0.600000,0.600000
289,I don't know .,I don't know .,0.000000,0.000000
290,mhm .,+< mhm .,0.333333,0.375000
291,okay .,+< okay .,0.333333,0.333333

# Baseline Aphasia Classifiers from CLAN Features of Manual Transcription

In [ ]:
#@title Baseline Logistic Regression
import pandas as pd

csv_path = f'drive/MyDrive/clan_features_with_labels.csv'
df = pd.read_csv(csv_path)
df.head()

,File,Language,Corpus,Code,Age,Sex,Group,Role,Duration_(sec),Total_Utts,...,Participant,Word comprehension,Sentence comprehension,Word finding,Grammatical construction,Speech motor programming,Repetition,Reading,Overall,Overall communication impairment
0,aprocsa1554a__G=Cat.cha,eng,APROCSA,PAR,46;00.,female,aphasia,Participant,0,6,...,1554,10.0,9.58,8.0,5.13,7.5,7.08,8.75,7.96,2.0
1,aprocsa1554a__G=Cinderella.cha,eng,APROCSA,PAR,46;00.,female,aphasia,Participant,0,15,...,1554,10.0,9.58,8.0,5.13,7.5,7.08,8.75,7.96,2.0
2,aprocsa1554a__G=Cinderella_Intro.cha,eng,APROCSA,PAR,46;00.,female,aphasia,Participant,0,3,...,1554,10.0,9.58,8.0,5.13,7.5,7.08,8.75,7.96,2.0
3,aprocsa1554a__G=Important_Event.cha,eng,APROCSA,PAR,46;00.,female,aphasia,Participant,0,130,...,1554,10.0,9.58,8.0,5.13,7.5,7.08,8.75,7.96,2.0
4,aprocsa1554a__G=Sandwich.cha,eng,APROCSA,PAR,46;00.,female,aphasia,Participant,0,3,...,1554,10.0,9.58,8.0,5.13,7.5,7.08,8.75,7.96,2.0

In [ ]:
from pathlib import Path

text_dir = Path("drive/MyDrive/par_text")  # change this if needed

transcripts = []
for i, row in df.iterrows():
    fname = row["File"].replace(".cha", ".txt")
    text_path = text_dir / fname

    if text_path.exists():
        transcripts.append(text_path.read_text())
    else:
        transcripts.append("")

df["transcript_text"] = transcripts

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from scipy.sparse import hstack
import numpy as np

exclude = [
    'File','Participant','Age','Sex','Group','Role',
    'Overall communication impairment','transcript_text'
]

clan_cols = [c for c in df.columns if c not in exclude]
clan_X = df[clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values

vectorizer = TfidfVectorizer(max_features=1000, ngram_range=(1,2))
text_X = vectorizer.fit_transform(df["transcript_text"])

scaler = StandardScaler()
clan_X_scaled = scaler.fit_transform(clan_X)

X = hstack([clan_X_scaled, text_X])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

y = df["Overall communication impairment"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

logreg = LogisticRegression(
    max_iter=2000,
    class_weight="balanced"  # important for small dataset
)

logreg.fit(X_train, y_train)

preds = logreg.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))

Accuracy: 0.9090909090909091
              precision    recall  f1-score   support

           1       1.00      0.50      0.67         2
           2       0.88      1.00      0.93         7
           3       1.00      1.00      1.00         2

    accuracy                           0.91        11
   macro avg       0.96      0.83      0.87        11
weighted avg       0.92      0.91      0.90        11

In [ ]:
#@title Baseline XG Boost

In [ ]:
import pandas as pd
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from scipy.sparse import hstack
import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load data
df = pd.read_csv('drive/MyDrive/clan_features_with_labels.csv')

# Load transcripts
text_dir = Path("drive/MyDrive/par_text")
transcripts = []
for i, row in df.iterrows():
    fname = row["File"].replace(".cha", ".txt")
    text_path = text_dir / fname
    if text_path.exists():
        transcripts.append(text_path.read_text())
    else:
        transcripts.append("")

df["transcript_text"] = transcripts

In [ ]:
# Prepare labels (convert to 0-indexed)
y = df["Overall communication impairment"].astype(int) - 1

# Train/test split
train_idx, test_idx = train_test_split(
    df.index, test_size=0.2, stratify=y, random_state=42
)

df_train = df.loc[train_idx]
df_test = df.loc[test_idx]
y_train = y.loc[train_idx]
y_test = y.loc[test_idx]

# Extract features
exclude = [
    'File','Participant','Age','Sex','Group','Role',
    'Overall communication impairment','transcript_text'
]

clan_cols = [c for c in df.columns if c not in exclude]

# CLAN features
clan_X_train = df_train[clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values
clan_X_test = df_test[clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values

# Fit scaler on train only
scaler = StandardScaler()
clan_X_train_scaled = scaler.fit_transform(clan_X_train)
clan_X_test_scaled = scaler.transform(clan_X_test)

# Fit vectorizer on train only
vectorizer = TfidfVectorizer(max_features=1000, ngram_range=(1,2))
text_X_train = vectorizer.fit_transform(df_train["transcript_text"])
text_X_test = vectorizer.transform(df_test["transcript_text"])

# Combine features
X_train = hstack([clan_X_train_scaled, text_X_train])
X_test = hstack([clan_X_test_scaled, text_X_test])

print(f"Dataset size: {len(df)} total, {len(train_idx)} train, {len(test_idx)} test")
print(f"Class distribution in test: {y_test.value_counts().sort_index().to_dict()}")

Dataset size: 54 total, 43 train, 11 test
Class distribution in test: {0: 2, 1: 7, 2: 2}

In [ ]:
# XGBoost model with heavy regularization
xgb = XGBClassifier(
    objective='multi:softprob',
    num_class=3,
    max_depth=2,
    n_estimators=30,
    learning_rate=0.05,
    min_child_weight=5,
    subsample=0.7,
    colsample_bytree=0.7,
    reg_alpha=1.0,
    reg_lambda=1.0,
    random_state=42
)
xgb.fit(X_train, y_train)
preds_xgb = xgb.predict(X_test)
acc_xgb = accuracy_score(y_test, preds_xgb)
print(f"Test Accuracy: {acc_xgb:.3f}")
print(classification_report(y_test, preds_xgb))

Test Accuracy: 0.636
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.64      1.00      0.78         7
           2       0.00      0.00      0.00         2

    accuracy                           0.64        11
   macro avg       0.21      0.33      0.26        11
weighted avg       0.40      0.64      0.49        11

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
#@title Baseline Naive Bayes

In [ ]:
import pandas as pd
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, train_test_split, StratifiedKFold
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.metrics import accuracy_score, classification_report
from scipy.sparse import hstack
import numpy as np

In [ ]:
# Load data
df = pd.read_csv('drive/MyDrive/clan_features_with_labels.csv')

# Load transcripts
text_dir = Path("drive/MyDrive/par_text")
transcripts = []
for i, row in df.iterrows():
    fname = row["File"].replace(".cha", ".txt")
    text_path = text_dir / fname
    if text_path.exists():
        transcripts.append(text_path.read_text())
    else:
        transcripts.append("")

df["transcript_text"] = transcripts

In [ ]:
# Prepare features
exclude = [
    'File','Participant','Age','Sex','Group','Role',
    'Overall communication impairment','transcript_text'
]

clan_cols = [c for c in df.columns if c not in exclude]
y = df["Overall communication impairment"].astype(int) - 1

print(f"Total dataset size: {len(df)}")
print(f"Class distribution:\n{y.value_counts().sort_index()}\n")

# Split data
train_idx, test_idx = train_test_split(
    df.index, test_size=0.2, stratify=y, random_state=42
)

df_train = df.loc[train_idx]
df_test = df.loc[test_idx]
y_train = y.loc[train_idx]
y_test = y.loc[test_idx]

Total dataset size: 54
Class distribution:
Overall communication impairment
0     9
1    36
2     9
Name: count, dtype: int64

In [ ]:
vectorizer = TfidfVectorizer(max_features=100, ngram_range=(1,2))
text_X_train = vectorizer.fit_transform(df_train["transcript_text"])
text_X_test = vectorizer.transform(df_test["transcript_text"])

nb_text = MultinomialNB()
nb_text.fit(text_X_train, y_train)
preds_text = nb_text.predict(text_X_test)

print(f"Test Accuracy: {accuracy_score(y_test, preds_text):.3f}")
print(f"\nClassification Report:")
print(classification_report(y_test, preds_text))

Test Accuracy: 0.636

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.64      1.00      0.78         7
           2       0.00      0.00      0.00         2

    accuracy                           0.64        11
   macro avg       0.21      0.33      0.26        11
weighted avg       0.40      0.64      0.49        11

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
clan_X_full = df[clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values
clan_X_full_scaled = StandardScaler().fit_transform(clan_X_full)

print("\n5-Fold CV Accuracy:")
cv_scores_clan = cross_val_score(
    GaussianNB(),
    clan_X_full_scaled,
    y,
    cv=5,
    scoring='accuracy'
)
print(f"Mean: {cv_scores_clan.mean():.3f} (+/- {cv_scores_clan.std():.3f})")
print(f"Individual folds: {cv_scores_clan}")

5-Fold CV Accuracy:
Mean: 0.982 (+/- 0.036)
Individual folds: [0.90909091 1.         1.         1.         1.        ]

In [ ]:
X_train_combined = hstack([clan_X_train_scaled, text_X_train]).toarray()
X_test_combined = hstack([clan_X_test_scaled, text_X_test]).toarray()

nb_combined = GaussianNB()
nb_combined.fit(X_train_combined, y_train)
preds_combined = nb_combined.predict(X_test_combined)

print(f"Test Accuracy: {accuracy_score(y_test, preds_combined):.3f}")
print(f"\nClassification Report:")
print(classification_report(y_test, preds_combined))

Test Accuracy: 0.727

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.70      1.00      0.82         7
           2       1.00      0.50      0.67         2

    accuracy                           0.73        11
   macro avg       0.57      0.50      0.50        11
weighted avg       0.63      0.73      0.65        11

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Baseline Dysarthria Classification with TORGO Datset

In [ ]:
#@title Load Dataset

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
data_dir = "drive/MyDrive/torgo_processed_data"
X = np.load(f"{data_dir}/X_mfcc.npy")
y = np.load(f"{data_dir}/Y.npy")

print(f"MFCC features: {X.shape}")
print(f"Labels: {y.shape}")

MFCC features: (8019, 128)
Labels: (8019,)

In [ ]:
print(f"\nTotal: {X.shape[0]} samples, {X.shape[1]} features")
print(f"Class distribution: {np.bincount(y)}")
print(f"  Class 0 (No dysarthria): {np.sum(y==0)}")
print(f"  Class 1 (Dysarthria): {np.sum(y==1)}")

Total: 8019 samples, 128 features
Class distribution: [5122 2897]
  Class 0 (No dysarthria): 5122
  Class 1 (Dysarthria): 2897

In [ ]:
#@title Baseline Logistic Regression

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"\nTrain samples: {len(X_train)}, Test samples: {len(X_test)}")

Train samples: 6415, Test samples: 1604

In [ ]:
logreg = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",  # Important for imbalanced data
    random_state=42
)

logreg.fit(X_train_scaled, y_train)

y_pred = logreg.predict(X_test_scaled)

print(f"Test Accuracy: {accuracy_score(y_test, y_pred):.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred,
                          target_names=['No Dysarthria', 'Dysarthria'],
                          digits=4))

Test Accuracy: 0.9582

Classification Report:
               precision    recall  f1-score   support

No Dysarthria     0.9669    0.9678    0.9673      1025
   Dysarthria     0.9429    0.9413    0.9421       579

     accuracy                         0.9582      1604
    macro avg     0.9549    0.9545    0.9547      1604
 weighted avg     0.9582    0.9582    0.9582      1604

In [ ]:
#@title Baseline Naive Bayes

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train: {len(X_train)}, Test: {len(X_test)}\n")

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Train: 6415, Test: 1604

In [ ]:
nb = GaussianNB()
nb.fit(X_train_scaled, y_train)
preds_nb = nb.predict(X_test_scaled)

print(f"Test Accuracy: {accuracy_score(y_test, preds_nb):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, preds_nb,
                          target_names=['No Dysarthria', 'Dysarthria']))

Test Accuracy: 0.7868

Classification Report:
               precision    recall  f1-score   support

No Dysarthria       0.83      0.84      0.83      1025
   Dysarthria       0.71      0.70      0.70       579

     accuracy                           0.79      1604
    macro avg       0.77      0.77      0.77      1604
 weighted avg       0.79      0.79      0.79      1604

In [ ]:
#@title Baseline XG Boost

In [ ]:
xgb = XGBClassifier(
    objective='binary:logistic',  # Binary classification
    max_depth=3,  # Shallow trees to prevent overfitting
    n_estimators=50,  # Fewer trees
    learning_rate=0.05,  # Slower learning
    min_child_weight=3,  # Require more samples per leaf
    subsample=0.8,  # Row sampling
    colsample_bytree=0.8,  # Column sampling
    reg_alpha=1.0,  # L1 regularization
    reg_lambda=1.0,  # L2 regularization
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train_scaled, y_train)
preds_xgb = xgb.predict(X_test_scaled)

print(f"Test Accuracy: {accuracy_score(y_test, preds_xgb):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, preds_xgb,
                          target_names=['No Dysarthria', 'Dysarthria']))

Test Accuracy: 0.9370

Classification Report:
               precision    recall  f1-score   support

No Dysarthria       0.93      0.98      0.95      1025
   Dysarthria       0.96      0.86      0.91       579

     accuracy                           0.94      1604
    macro avg       0.94      0.92      0.93      1604
 weighted avg       0.94      0.94      0.94      1604

In [ ]:
#@title Basic CNN

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import tensorflow as tf
from tensorflow import keras

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

print(f"Reshaped: {X_train.shape}")

Reshaped: (6415, 128, 1)

In [ ]:
#@title 1-Layer CNN
model = keras.Sequential([
    keras.layers.Conv1D(16, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)),
    keras.layers.Flatten(),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20, batch_size=16, verbose=1)

y_pred = (model.predict(X_test, verbose=0) > 0.5).astype(int).flatten()
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(classification_report(y_test, y_pred, target_names=['No Dysarthria', 'Dysarthria']))

Epoch 1/20

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

401/401 ━━━━━━━━━━━━━━━━━━━━ 8s 13ms/step - accuracy: 0.8717 - loss: 0.3161
Epoch 2/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9739 - loss: 0.0858
Epoch 3/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9823 - loss: 0.0649
Epoch 4/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9883 - loss: 0.0448
Epoch 5/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9881 - loss: 0.0410
Epoch 6/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9877 - loss: 0.0399
Epoch 7/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9912 - loss: 0.0320
Epoch 8/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9902 - loss: 0.0329
Epoch 9/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9923 - loss: 0.0262
Epoch 10/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9948 - loss: 0.0224
Epoch 11/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9941 - loss: 0.0231
Epoch 12/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9953 - loss: 0.0196
Epoch 13/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9932 - loss: 0.0202
Epoch 14/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9948 - loss: 0.0189
Epoch 15/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9970 - loss: 0.0152
Epoch 16/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9968 - loss: 0.0131
Epoch 17/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9942 - loss: 0.0152
Epoch 18/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9975 - loss: 0.0107
Epoch 19/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9981 - loss: 0.0100
Epoch 20/20
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9981 - loss: 0.0099
Accuracy: 0.9832
               precision    recall  f1-score   support

No Dysarthria       0.99      0.98      0.99      1025
   Dysarthria       0.97      0.98      0.98       579

     accuracy                           0.98      1604
    macro avg       0.98      0.98      0.98      1604
 weighted avg       0.98      0.98      0.98      1604

In [ ]:
#@title 3-Layer CNN
model = keras.Sequential([
    keras.layers.Conv1D(32, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)),
    keras.layers.MaxPooling1D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=30, batch_size=16, verbose=1)

y_pred = (model.predict(X_test, verbose=0) > 0.5).astype(int).flatten()

print(f"\nAccuracy: {accuracy_score(y_test, y_pred):.4f}")
print(classification_report(y_test, y_pred, target_names=['No Dysarthria', 'Dysarthria']))

Epoch 1/30

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

401/401 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8313 - loss: 0.3685
Epoch 2/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9641 - loss: 0.1180
Epoch 3/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9721 - loss: 0.0893
Epoch 4/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9813 - loss: 0.0634
Epoch 5/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9842 - loss: 0.0555
Epoch 6/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9799 - loss: 0.0575
Epoch 7/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9849 - loss: 0.0494
Epoch 8/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9865 - loss: 0.0449
Epoch 9/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9871 - loss: 0.0413
Epoch 10/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9854 - loss: 0.0421
Epoch 11/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9885 - loss: 0.0357
Epoch 12/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9907 - loss: 0.0331
Epoch 13/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9915 - loss: 0.0283
Epoch 14/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9902 - loss: 0.0316
Epoch 15/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9951 - loss: 0.0221
Epoch 16/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9909 - loss: 0.0260
Epoch 17/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9925 - loss: 0.0282
Epoch 18/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9933 - loss: 0.0236
Epoch 19/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9934 - loss: 0.0234
Epoch 20/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9922 - loss: 0.0236
Epoch 21/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9936 - loss: 0.0169
Epoch 22/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9928 - loss: 0.0202
Epoch 23/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9954 - loss: 0.0154
Epoch 24/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9945 - loss: 0.0165
Epoch 25/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9966 - loss: 0.0170
Epoch 26/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9952 - loss: 0.0156
Epoch 27/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9956 - loss: 0.0136
Epoch 28/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9970 - loss: 0.0127
Epoch 29/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9956 - loss: 0.0136
Epoch 30/30
401/401 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9971 - loss: 0.0128

Accuracy: 0.9844
               precision    recall  f1-score   support

No Dysarthria       0.99      0.99      0.99      1025
   Dysarthria       0.98      0.98      0.98       579

     accuracy                           0.98      1604
    macro avg       0.98      0.98      0.98      1604
 weighted avg       0.98      0.98      0.98      1604

#  Unsupervised Clustering of Baseline Whisper Transcription using TF-IDF

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
baseline_whisper_df = pd.read_csv('drive/MyDrive/baseline_whisper_preds.csv')

In [ ]:
# Extract features
X_text = baseline_whisper_df['hypothesis'].fillna("")
print(f"Total samples: {len(X)}")

vectorizer = TfidfVectorizer(max_features=1000, ngram_range=(1, 2))
X_tfidf = vectorizer.fit_transform(X_text)
print(f"TF-IDF features shape: {X_tfidf.shape}")

Total samples: 264
TF-IDF features shape: (264, 1000)

In [ ]:
# KMeans Clustering
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_tfidf)
baseline_whisper_df['cluster'] = clusters

print(f"\nCluster distribution: {pd.Series(clusters).value_counts().sort_index().to_dict()}")
for i in range(3):
    print(f"\nCluster {i} sample:")
    print(f"  \"{baseline_whisper_df[baseline_whisper_df['cluster']==i]['hypothesis'].iloc[0][:80]}...\"")

Cluster distribution: {0: 8, 1: 124, 2: 132}

Cluster 0 sample:
  " Okay...."

Cluster 1 sample:
  " It was still a challenge...."

Cluster 2 sample:
  " You can write next...."

# Unsupervised Clustering of Finetuned Whisper Transcription using TF-IDF

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
finetuned_whisper_df = pd.read_csv('drive/MyDrive/finetuned_whisper_preds.csv')

In [ ]:
# Extract features
X_text = finetuned_whisper_df['hypothesis'].fillna("")
print(f"Total samples: {len(X)}")

vectorizer = TfidfVectorizer(max_features=1000, ngram_range=(1, 2))
X_tfidf = vectorizer.fit_transform(X_text)
print(f"TF-IDF features shape: {X_tfidf.shape}")

Total samples: 264
TF-IDF features shape: (292, 1000)

In [ ]:
# KMeans Clustering
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_tfidf)
finetuned_whisper_df['cluster'] = clusters

print(f"\nCluster distribution: {pd.Series(clusters).value_counts().sort_index().to_dict()}")
for i in range(3):
    print(f"\nCluster {i} sample:")
    print(f"  \"{finetuned_whisper_df[finetuned_whisper_df['cluster']==i]['hypothesis'].iloc[0][:80]}...\"")

Cluster distribution: {0: 22, 1: 21, 2: 249}

Cluster 0 sample:
  " So ‡ okay ...."

Cluster 1 sample:
  " mhm ...."

Cluster 2 sample:
  " alright ...."

# End to end classification pipeline

In [ ]:
PARTICIPANT_NUMS = ["1554", "1713", "1731", "1738", "1833", "1944"]
MAX_AUDIO_ARRAY_LEN = 30 * 16000

In [ ]:
#@title Make dataset

import random

participant_num = PARTICIPANT_NUMS[random.randint(0, len(PARTICIPANT_NUMS))]

audio_array = librosa.load(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{participant_num}/video.mp4')
audio_array = librosa.resample(audio_array[0], orig_sr=audio_array[1], target_sr=16000)

dataset_output_path = f'drive/MyDrive/{APROCSA_DATASET_LOC}/{participant_num}/dataset.json'
data = []
i = 0
while i * MAX_AUDIO_ARRAY_LEN < len(audio_array):
  data.append({"i": i, "audio": audio_array[i*MAX_AUDIO_ARRAY_LEN:min(len(audio_array), (i+1)*MAX_AUDIO_ARRAY_LEN)].tolist()})
  i += 1

with open(dataset_output_path, 'w') as f:
  json.dump({"data": data}, f)

/tmp/ipython-input-2439631253.py:7: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_array = librosa.load(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{participant_num}/video.mp4')
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
dataset = load_dataset("json", data_files=dataset_output_path, field="data", split="train")

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
model_checkpoint = "drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/finetuning/checkpoint-1200"

In [ ]:
#@title Set up model, tokenizer, and feature extractor
from transformers import WhisperForConditionalGeneration

device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model = WhisperForConditionalGeneration.from_pretrained(model_checkpoint)
model.to(device)

tokenizer = WhisperTokenizer.from_pretrained(model_checkpoint)
feature_extractor = WhisperFeatureExtractor.from_pretrained(MODEL_ID)

HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/finetuning/checkpoint-1200'. Use `repo_type` argument if needed.

In [ ]:
## Code is based on model card for Whispr on HuggingFace (https://huggingface.co/openai/whisper-large-v3)
results = []
for batch in dataset.batch(batch_size=4):
  audio_arrays = batch["audio"]
  features = feature_extractor(audio_arrays, sampling_rate=16000, return_tensors="pt").input_features.to(device)
  with torch.no_grad():
    prediction_ids = model.generate(inputs=features)
  predictions = tokenizer.batch_decode(prediction_ids, skip_special_tokens=True)
  results.append({"predictions": predictions, "id": batch["i"]})

sorted_results = sorted(results, key=lambda x: x["id"])

Batching examples:   0%|          | 0/117 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/models/whisper/generation_whisper.py:655: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
Using custom `forced_decoder_ids` from the (generation) config. This is deprecated in favor of the `task` and `language` flags/config options.
Transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English. This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`. See https://github.com/huggingface/transformers/pull/28687 for more details.
`generation_config` default values have been modified to match model-specific defaults: {'suppress_tokens': [1, 2, 7, 8, 9, 10, 14, 25, 26, 27, 28, 29, 31, 58, 59, 60, 61, 62, 63, 90, 91, 92, 93, 359, 503, 522, 542, 873, 893, 902, 918, 922, 931, 1350, 1853, 1982, 2460, 2627, 3246, 3253, 3268, 3536, 3846, 3961, 4183, 4667, 6585, 6647, 7273, 9061, 9383, 10428, 10929, 11938, 12033, 12331, 12562, 13793, 14157, 14635, 15265, 15618, 16553, 16604, 18362, 18956, 20075, 21675, 22520, 26130, 26161, 26435, 28279, 29464, 31650, 32302, 32470, 36865, 42863, 47425, 49870, 50254, 50258, 50359, 50360, 50361, 50362, 50363], 'begin_suppress_tokens': [220, 50257]}. If this is not desired, please set these values explicitly.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.

In [ ]:
from openai import OpenAI
from google.colab import userdata

os.environ["OPENAI_API_KEY"] = userdata.get('229-open-ai-api-key')

client = OpenAI()

def speaker_diarization(transcript):
  response = client.responses.create(
      model="gpt-5.1",
      instructions="You are given a transcript between and interviewer and a participant. Your task is toannotate the transcript to add a speaker tag before each speaker begins talking. The interviewer's speaker tag is *INV and the participant's speaker tag is *PAR. Return only the annotated transcript with no other changes",
      input=transcript
  )

  return response.output_text

In [ ]:
print(sorted_results)

In [ ]:
full_transcript = " ".join([" ".join(r["predictions"]) for r in sorted_results])
diarized_transcript = speaker_diarization(full_transcript)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{participant_num}/full_transcript.txt', 'w') as f:
  f.write(diarized_transcript)

## Transcript feature extraction

- Utterance metrics: Total_Utts, MLU_Utts (mean length of utterance from morphemes), MLU_Words (mean length of utterance in words), MLU_Morphemes
- Lexical metrics: FREQ_types, FREQ_tokens, FREQ_TTR, Words_Min
- Grammatical features: %_Nouns, %_Verbs, %_Aux, %_Mod, %_PAST, %_PRESP, %_prep, %_adj, %_adv, etc.
- Error metrics: %_Word_Errors, Utt_Errors, retracing, repetition
- Other features: density, noun_verb, open_closed, #open-class, #closed-class

From https://talkbank.org/0info/manuals/CLAN.pdf

In [ ]:
#@title Util functions for getting utterance metrics
def get_all_utterances(transcript, speaker):
  all_utterances = []
  for line in transcript.split("\n"):
    if not speaker in line:
      continue

    all_utterances.extend(line[4:].split(" ."))
  return all_utterances

def get_utterance_features(transcript, speaker):
  all_utterances = get_all_utterances(transcript, speaker)

  total_utterances = len(all_utterances)

  utterance_words = []
  for utt in all_utterances:
    utterance_words.extend(utt.split(" "))

  return {
      "total_utts": total_utterances,
      "mlu_utts": None,
      "mlu_words": None
  }

In [ ]:
#@title Util functions for getting lexical features
def get_all_words(transcript, speaker):
  all_words = []
  for line in transcript.split("\n"):
    if not speaker in line:
      continue

    utterances = line[4:].split(" .")
    for utt in utterances:
      all_words.extend(utt.split(" "))
  return all_words

def get_unique_words(all_words):
  return list(set(all_words))

def get_lexical_features(transcript, dataset, speaker):
  all_words = get_all_words(transcript, speaker)
  unique_words = get_unique_words(all_words)

  # length of the recording in minutes, audio is sampled at 16kHz
  audio_len = np.sum(np.array([len(audio) for audio in dataset["audio"]]))
  length = int(audio_len) / 16000 / 60

  return {
      "FREQ_types": len(unique_words),
      "FREQ_tokens": len(all_words),
      "FREQ_TTR": len(unique_words) / len(all_words),
      "Words_Min": len(all_words) / length
  }

In [ ]:
#@title Util functions for extracting grammatical features
from openai import OpenAI
from google.colab import userdata
from pydantic import BaseModel

os.environ["OPENAI_API_KEY"] = userdata.get('229-open-ai-api-key')

client = OpenAI()

class GrammaticalTypes(BaseModel):
  nouns: int
  verbs: int
  adjectives: int
  adverbs: int
  present_participles: int
  past_participles: int
  past_tense: int
  auxiliaries: int
  modals: int
  pronouns: int
  third_person_singular: int
  first_person_singular: int
  prepositions: int
  conjunctions: int
  determiners: int
  plurals: int

  def to_obj(self):
    return {
        "nouns": self.nouns,
        "verbs": self.verbs,
        "adj": self.adjectives,
        "adv": self.adverbs,
        "PresP": self.present_participles,
        "PastP": self.past_participles,
        "Past": self.past_tense,
        "aux": self.auxiliaries,
        "mod": self.modals,
        "pro": self.pronouns,
        "3S": self.third_person_singular,
        "prep": self.prepositions,
        "conj": self.conjunctions,
        "det": self.determiners,
        "plurals": self.plurals
    }

def get_percent_classes(grammatical_types_obj, all_words):
  result = {}
  for key, val in grammatical_types_obj.items():
    result[f'%_{key}'] = val / len(all_words)
  return result

OPEN_CLASSES = ["nouns", "adv", "adj", "verbs"]
OPEN_EXCLUDED = ["aux", "mod"]
def get_grammatical_features(transcript, speaker):
  all_words = get_all_words(transcript, speaker)
  grammatical_types = client.responses.parse(
      model="gpt-5.1",
      instructions="You are given a list of words, extract number of words of each grammatical type.",
      input=transcript,
      text_format=GrammaticalTypes
  ).output_parsed

  types_obj = grammatical_types.to_obj()

  result = get_percent_classes(types_obj, all_words)

  open_class_words = int(np.sum(np.array([types_obj[class_type] for class_type in OPEN_CLASSES])) - np.sum(np.array([types_obj[class_type] for class_type in OPEN_EXCLUDED])))
  closed_class_words = len(all_words) - open_class_words

  density_num_classes = ["verbs", "adjectives", "adverbs", "prepositions", "conjunctions"]
  density = int(np.sum(np.array([types_obj[class_type] for class_type in density_num_classes]))) / len(all_words)

  result["noun_verb"] = types_obj["nouns"] / types_obj["verbs"]
  result["open_closed"] = open_class_words / closed_class_words
  result["#open-class"] = open_class_words
  result["#closed-class"] = closed_class_words
  result["density"] = density

  return result

In [ ]:
import csv

grammatical_features = get_grammatical_features(diarized_transcript, "*PAR")
lexical_features = get_lexical_features(diarized_transcript, dataset, "*PAR")
utterance_features = get_utterance_features(diarized_transcript, "*PAR")

all_features = grammatical_features | lexical_features | utterance_features
print(all_features)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{participant_num}/output_features.csv', 'w') as f:
  headers = list(all_features.keys())
  writer = csv.DictWriter(f, fieldnames=headers)

  writer.writeheader()
  writer.writerow(all_features)

NameError: name 'diarized_transcript' is not defined

# Generate

In [ ]:
#@title Make dataset

import random

for participant_num in PARTICIPANT_NUMS:
  print("Begin Participant", participant_num)
  audio_array = librosa.load(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{participant_num}/video.mp4')
  audio_array = librosa.resample(audio_array[0], orig_sr=audio_array[1], target_sr=16000)

  dataset_output_path = f'drive/MyDrive/{APROCSA_DATASET_LOC}/{participant_num}/dataset.json'

  data = []
  i = 0
  while i * MAX_AUDIO_ARRAY_LEN < len(audio_array):
    data.append({"i": i, "audio": audio_array[i*MAX_AUDIO_ARRAY_LEN:min(len(audio_array), (i+1)*MAX_AUDIO_ARRAY_LEN)].tolist()})
    i += 1

  with open(dataset_output_path, 'w') as f:
    json.dump({"data": data}, f)

  print("End Participant", participant_num)

Begin Participant 1944

/tmp/ipython-input-3728532962.py:8: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_array = librosa.load(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{participant_num}/video.mp4')
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

End Participant 1944

In [ ]:
#@title Set up model, tokenizer, and feature extractor
from transformers import WhisperForConditionalGeneration

model_checkpoint = "drive/MyDrive/cs229_final_proj/finetuning/checkpoint-1200"

device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model = WhisperForConditionalGeneration.from_pretrained(model_checkpoint)
model.to(device)

tokenizer = WhisperTokenizer.from_pretrained(model_checkpoint)
feature_extractor = WhisperFeatureExtractor.from_pretrained(MODEL_ID)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
from openai import OpenAI
from google.colab import userdata

os.environ["OPENAI_API_KEY"] = userdata.get('229-open-ai-api-key')

client = OpenAI()

def speaker_diarization(transcript):
  response = client.responses.create(
      model="gpt-5.1",
      instructions="You are given a transcript between and interviewer and a participant. Your task is toannotate the transcript to add a speaker tag before each speaker begins talking. The interviewer's speaker tag is *INV and the participant's speaker tag is *PAR. Return only the annotated transcript with no other changes",
      input=transcript
  )

  return response.output_text

# 1713

In [ ]:
dataset_output_path = f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1713"}/dataset.json'
dataset = load_dataset("json", data_files=dataset_output_path, field="data", split="train")

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
results = []
for batch in dataset.batch(batch_size=4):
  audio_arrays = batch["audio"]
  features = feature_extractor(audio_arrays, sampling_rate=16000, return_tensors="pt").input_features.to(device)
  with torch.no_grad():
    prediction_ids = model.generate(inputs=features)
  predictions = tokenizer.batch_decode(prediction_ids, skip_special_tokens=True)
  results.append({"predictions": predictions, "id": batch["i"]})

sorted_results = sorted(results, key=lambda x: x["id"])
print(sorted_results)

`generation_config` default values have been modified to match model-specific defaults: {'suppress_tokens': [1, 2, 7, 8, 9, 10, 14, 25, 26, 27, 28, 29, 31, 58, 59, 60, 61, 62, 63, 90, 91, 92, 93, 359, 503, 522, 542, 873, 893, 902, 918, 922, 931, 1350, 1853, 1982, 2460, 2627, 3246, 3253, 3268, 3536, 3846, 3961, 4183, 4667, 6585, 6647, 7273, 9061, 9383, 10428, 10929, 11938, 12033, 12331, 12562, 13793, 14157, 14635, 15265, 15618, 16553, 16604, 18362, 18956, 20075, 21675, 22520, 26130, 26161, 26435, 28279, 29464, 31650, 32302, 32470, 36865, 42863, 47425, 49870, 50254, 50258, 50359, 50360, 50361, 50362, 50363], 'begin_suppress_tokens': [220, 50257]}. If this is not desired, please set these values explicitly.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.

[{'predictions': [' Okay .', ' Oh okay. Could you tell me about it ?', " um well ‡ um I woke up and um um sit up and um it didn't feel strange or anything and I got up to go to the bathroom &-laughs and I couldn't get my arm &-ges to do something and I  I  d it didn't really dawn on me „ you know . So I came out and tried to make a  a coffee .", " I just couldn't make it &//laughs and I uh turned around and I fell and I didn't understand why I fell and um I went back in the room . My um granddaughter was spending the night and um I decided that um um I needed some help you-know and um"], 'id': [0, 1, 2, 3]}, {'predictions': [" I tried to call my son but I didn't  I didn't work you-know and my daughter came up and I d called her and all I could say was yeah  yeah  ya you-know that's all I could say um um and um then after I s fell again &-laughs and my daughter um I mean my granddaughter um", " uh took my phone and ran out here and called her dad you know . So that was you know the  got the ambulance and everything so . That's good she was there . Yeah &//laughs . Well I think she was afraid because she uh come out of the bedroom and stayed back here waiting for them you know she didn't &//laughs .", " &-laughs yeah  how old was she ? um I don't know ten , eleven yeah  oh okay then yeah scary but well I'm glad to hear that it's been getting better though so that's  that's actually the next question I think . Yes okay . So um I'd like to hear about your recovery and what kinds of things you've done to try and get better since your stroke .", ' I go to the gym um and do uh water aerobics .'], 'id': [4, 5, 6, 7]}, {'predictions': [" ja jotain um treadmilla . Ja um that's youknow it  that's it . I don't do um um therapy anymore because I can't afford it &-laughs youknow . Um I  um I r like to read but I don't like it now youknow .", " I have to read it two or three books a a week you know yeah and I  um there's a book I've had since um uh beginning of September and I still haven't finished it yet you know but I try to read out loud and um some words that I can't per not pronounce I stay on them .", ' Have you tried books on tape ?', " I s I can't talk ."], 'id': [8, 9, 10, 11]}, {'predictions': [" to you unless it's like a podcast while I'm driving or I have to be doing something else or some brain doesn't listen . I can do it while driving you-know but I don't drive that much &-laughs so you-know .", ' Okay .', " se oli se ja hänne olen delivered you know um we're  we're in the parking lot of  of a bank trying to get some money to put gas in the car &//laughs . Wow . Yeah but you know she  w she was fine you know um um she was the third one so you know we pretty much knew what was the deal &//laughs .", ' yeah ‡ better than if it was the first one you had „ yeah .'], 'id': [12, 13, 14, 15]}, {'predictions': [" By the time they got to the lobby it was it was time . Yeah yeah . So it sounds similar . It w w uh it's called precipitous labor . But you know I just had one  I had one pain and I got everybody up &//laughs and ready and I had another pain um um when I reached the car and then you know &//ges .", " um yeah but then I pushed so &//laughs yeah &//laughs wow that's pretty . How many kids do you have ? Three . Oh okay . Okay so ‡ that was the last one you had . Yeah  yeah . Okay .", " of time to look at those pictures . They tell a story . Mm hm . And so if you look at all of them , then I'll ask you to tell me a story with a beginning , middle and end . And you can look at the pictures while you tell the story . Okay &//laughs .", ' um she  she said  she said yes .'], 'id': [16, 17, 18, 19]}, {'predictions': [" I um the mother was  wants him to use an umbrella and he said I don't need it and she  um when he gets outside it's raining and raining bad and he comes back to his mother and said I need an umbrella and you know there's the umbrella . A story  are you familiar with feeling that way if your kids ever not listen to you ? Oh yeah  yeah .", " okay um so ‡ this is the last picture . So there's a lot going on . Look at everything that's happening and then tell me again a story about you  what you see with a beginning , middle and end if you can .", " Cat is in the tree  um  m  um   &-laughs um missing I mean  the girl wants her cat and um the fire truck is there  I don't know if she's going to get the dog or the cat down you-know &-thes both &-laughs yep  yep", " Yeah ‡ I feel like cats are stubborn if they just waiting like this and don't think anything's gonna happen &//laughs . Okay ‡ so ‡ next I'm gonna ask you to tell a story . Okay . So ‡ have you ever heard the story of Cinderella ? Yeah ."], 'id': [20, 21, 22, 23]}, {'predictions': [" and then I'll put the book away and ask you to tell me the story in your own words . Okay . So go ahead and just flip through and you'll tell me the story after you look through them . Okay .", ' Mhm .', " I'll never  I mean I'll never remember Fairy Godmother and everything &//laughs .", ' okay .'], 'id': [24, 25, 26, 27]}, {'predictions': [' .', " Her father kept um uh t care of her and um she needed a mother so she got um a stepmother but uh she wasn't very nice and the father died and ever since the father died she was real mean to um Cinderella and Maisel .", ' , সা সা  সা   ', ' um maiden in the land &-laughs to um come to see if the prince was interested &-laughs and um um she  um Cinderella wanted to go . So she busied herself all up with you know the preparations and um for secretly she made a dress and um'], 'id': [28, 29, 30, 31]}, {'predictions': [' it was time to leave and um um they said um there was some things on her um gown that were her sisters you-know like uh the ribbons and stuff like that and anyway um she um ta to tore it to shreds and so she said it was time to leave .', ' so um the s stepmother and stepsisters you know took  um took off for the ball and Cinderella um cried and suddenly she saw a fairy godmother , godmother &-laughs and um um she gave  no she gave  no .', " well ‡ anyway &-laughs she gave her a  f a pretty dress to wear and she made a pumpkin into a um coach and she made field mice into footmen . And she said be back by twelve o'clock you know and sh um Cinderella went to the ball .", " It's with the prince and everything and it struck midnight and she had to get away and um anyway um she got away but the by the time she went  um by the time she got back um her clothes were um all gone and y y n um the prince was all gone ."], 'id': [32, 33, 34, 35]}, {'predictions': [" the coach and all had um disappeared um &//laughs um but only um she had one um slipper , a gold slipper um and anyway um &//laughs sorry your dog is &//laughs here it is &//laughs that's why I'm laughing .", ' Anyway &//laughs um um the  um the call went out that the prince was looking for someone to fit in the slipper . And the um stepmother and the stepsisters um', " were  were ready for them and they uh came and um the  uh but  sh but &-laughs it doesn't fit  it didn't fit them and um anyway um Cinderella come and sh I  .", ' um anyway Cinderella came and um she tried the slipper on and you know they lived xxx you know &//laughs .'], 'id': [36, 37, 38, 39]}, {'predictions': [" I hear someone tell us I learn more than what I previously knew &//laughs . Okay so I have one last um talking thing and then we'll go on to the language test . Okay . So um this is a little different . Tell me how you would make a peanut butter and jelly sandwich .", ' you  lift it out of the  jar and you spread it and then you take the peanut butter and you lift it out  I mean the  the jelly and you lift it out of the jelly and you spread it on one or  uh the other side of the bread and you put it together  hm I got it  okay', " do your grandkids eat pb & j's yeah yeah I always think that's funny because I haven't had a youknow butter and jelly since I was younger probably except maybe from hospital food or something well you you should try it okay so", " so we're done with all the talking stuff &-laughs um so next I'm gonna ask you what is happening in these pictures . So first just go ahead and tell me what's happening in that picture . Just that one um um she  he is giving her a bath mhm"], 'id': [40, 41, 42, 43]}, {'predictions': [" second picture she is kicking him yep &//laughs . I have trouble sometimes because um because of he and she &//ges uh I get them confused yeah it's  I've noticed that a lot with a lot of people it's very common I would say yeah I would say you know he and um everybody would say she and I said I know &//laughs .", " Who's correcting you ? That's the problem here . Is it where you know it in your head but it doesn't come out the right way ? Yes  I know  yes . Well ‡ I know that I'm saying it wrong &-ges but you know &-ges . Right . Yeah . It's just hard to control it because  yeah .", ' point to the things that I said . Okay . So show me the guitar . Show me the tiger . Show me the zebra . Show me the saxophone . Great . Okay . So same thing . Show me the pear . Show me the crown .', " Oh. And show me the cloud. Show me the chair. Okay. So now I'm gonna ask you some questions that  um and I want you to answer yes or no . Okay . Okay . So are you sitting ? Yes . Am I standing ? No ."], 'id': [44, 45, 46, 47]}, {'predictions': [" Do you eat ice cream with a spoon ? Yes. Are spiders bitten by people ? No . Do you wear gloves on your feet ? No . If you're about to go outside , are you still inside ? Yes . Are worms eaten by birds ? Yes .", " It's so spooky .", " Yes. That's good ‡ okay . So next I'm gonna show you some more pictures . Okay so what is this ? A book . Mhm and this ?", " seahorse  and then  pyramid . Yeah ‡ that was great . Okay ‡ you're flying through these &-laughs so we're already at this version . Okay so  um so I'm gonna have you write what these pictures are and you can use a pen . I can't spell very well ."], 'id': [48, 49, 50, 51]}, {'predictions': [" okay . Has that been since your stroke or is that ? Yes no it's been for my stroke . Before okay . No no it's been after my stroke .", " Anyway um yeah um I can  I can spell not very well &//laughs . Okay . That's okay . I know it's a mushroom &//laughs .", ' uhhuh ‡ you got it .', ' um um'], 'id': [52, 53, 54, 55]}, {'predictions': [" and they're the end to M2 . Do you wanna try writing ? Okay . So next um I just want you to repeat after me . Okay . Man . Man . Blanket . Blanket . Prosperity .", " Prosperity . Insignificant . Insignificant . This one's appropriate . The dog barks at the door . The dog barks at the door . Okay . This one's longer . The creative architect understood who we'd be seeing .", " yeah um the creative architect understood who we'd be seeing . The creative architect understood who she  who she would be seeing ? Yeah . That was great . I know that one's trickier and longer &-laughs .", " Make sure I'm on the right page so I don't say show me something that's not there . Okay so show me the elephant . Show me the piano . Show me the camel . Show me the trumpet ."], 'id': [56, 57, 58, 59]}, {'predictions': [' okay ‡ show me the cat . Show me the box . Show me the cane . Show me the socks . Okay ‡ so ‡ some more yes no questions .', ' okay okay are you wearing a green shirt no I always have to make sure I say that one right &//laughs it depends on the person do you brush your teeth with a comb no are babies named by parents no yes', ' Yes. No. Yes. Yes.', " no no . Almost got you . You got it . If he was at the show when you arrived did he get there first ? Yes . Are thieves robbed by victims ? No . If I tell you I used to drink coffee do you think I drink coffee now ? No . That was great . I was looking back too because um to see because you've done your show ."], 'id': [60, 61, 62, 63]}, {'predictions': [" these kinds of questions before and this is even I mean  this is fantastic & it's even more than you got the last time & you did really well the last time . Oh ‡ okay . Yeah ‡ you've got all of these correct . Okay . So next I'm gonna have you read out loud .", ' Έχει και έτσι &//laughs.', " Next I'm gonna show you some more pictures with a word and I want you to show me the picture that matches the word in the middle okay", ' mhm  okay .'], 'id': [64, 65, 66, 67]}, {'predictions': [" you to do some of those motor things that I'm sure you've done in the past . Um so could you stick your tongue out for me and then can you move it from side to side ? mhm . Okay and next I want you to say ah for as long as you can .", " that was funny . Okay um so next I want you to say pa as um steadily as you can so as fast and as steady of a rhythm . Okay pa pa pa pa pa pa pa pa pa pa . That's great yeah could you um try faster but also keep it steady if you can .", ' uh pa pa pa pa pa pa pa .', ' Okay .'], 'id': [68, 69, 70, 71]}, {'predictions': [' catastrophe  catastrophe . yeah okay . And last I just want you to count to ten . one two three four five six seven eight nine ten .'], 'id': [72]}]

In [ ]:
full_transcript = " ".join([" ".join(r["predictions"]) for r in sorted_results])
diarized_transcript = speaker_diarization(full_transcript)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1713"}/full_transcript.txt', 'w') as f:
  f.write(diarized_transcript)

In [ ]:
import csv

grammatical_features = get_grammatical_features(diarized_transcript, "*PAR")
lexical_features = get_lexical_features(diarized_transcript, dataset, "*PAR")
utterance_features = get_utterance_features(diarized_transcript, "*PAR")

all_features = grammatical_features | lexical_features | utterance_features
print(all_features)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1713"}/output_features.csv', 'w') as f:
  headers = list(all_features.keys())
  writer = csv.DictWriter(f, fieldnames=headers)

  writer.writeheader()
  writer.writerow(all_features)

{'%_nouns': 0.10063559322033898, '%_verbs': 0.08686440677966102, '%_adj': 0.00847457627118644, '%_adv': 0.02065677966101695, '%_PresP': 0.011122881355932203, '%_PastP': 0.003707627118644068, '%_Past': 0.04396186440677966, '%_aux': 0.03919491525423729, '%_mod': 0.005296610169491525, '%_pro': 0.06991525423728813, '%_3S': 0.019067796610169493, '%_prep': 0.04449152542372881, '%_conj': 0.06673728813559322, '%_det': 0.06726694915254237, '%_plurals': 0.019597457627118644, 'noun_verb': 1.1585365853658536, 'open_closed': 0.20793346129238643, '#open-class': 325, '#closed-class': 1563, 'FREQ_types': 447, 'FREQ_tokens': 1888, 'FREQ_TTR': 0.2367584745762712, 'Words_Min': 52.08133087386053, 'total_utts': 171, 'mlu_utts': None, 'mlu_words': None}

# 1731

In [ ]:
dataset_output_path = f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1731"}/dataset.json'
dataset = load_dataset("json", data_files=dataset_output_path, field="data", split="train")

In [ ]:
results = []
for batch in dataset.batch(batch_size=4):
  audio_arrays = batch["audio"]
  features = feature_extractor(audio_arrays, sampling_rate=16000, return_tensors="pt").input_features.to(device)
  with torch.no_grad():
    prediction_ids = model.generate(inputs=features)
  predictions = tokenizer.batch_decode(prediction_ids, skip_special_tokens=True)
  results.append({"predictions": predictions, "id": batch["i"]})

sorted_results = sorted(results, key=lambda x: x["id"])
print(sorted_results)

/usr/local/lib/python3.12/dist-packages/transformers/models/whisper/generation_whisper.py:655: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

[{'predictions': [" okay ‡ so ‡ first we're just gonna do some talking .", ' um Jennifer  Jennifer . Oh mhm . Yeah , Jennifer . Speaking . Mhm . I know her . Mhm . Ruh really ? Mhm . Miss you a lot . Aww . Yeah . Um so ‡ okay . Do you remember when you had your stroke ? Yes indeed . Mhm .', ' .', " mhm . Or just for  but uh flying helicopters . mhm . Two weeks . mhm . Sleeping . mhm . mhm . That's really hard . Yeah ‡ right . But what can you do ? mhm . So ‡ what about after that ? What happened next ? Tutingen Germany uh ."], 'id': [0, 1, 2, 3]}, {'predictions': [' This one um...', ' god and uh Saudi and uh Felix and Tamra and  &//ges and sleeping and flying Germany and um uh what can you do but uh &//ges and then &//ges the  the  the  the  the and cut off  cut off the cut off . ', ' & .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .).) .)so  & &-Gay . ', ' soddy . '], 'id': [4, 5, 6, 7]}, {'predictions': [' wheelchair or just  oh I see ‡ okay .', ' .', ' on that note . So what kinds of things have you done to try and get better since your stroke ? Yeah better . What have you done to try and get better ?', ' me  uh one bedroom  bedroom me and walking running treadmill all the time  m let the  go step all the time „ Monday , Tuesday , Wednesday and uh Monday , Tuesday , Wednesday &-Gods Thursday listening to people and s uh reading books  reading books .'], 'id': [8, 9, 10, 11]}, {'predictions': [' reading books . ', ' to Vanderbilt oh my god one two years one two three years ago okay so that definitely family oh my god yes a long time to be uh this one uh domin  uh um this one um um', " Dominick no oh oh my god um Josh and  uh r uh Josh and &//ges.) Mindy .).) Mindy . It's family . Yeah family . Josh and Mindy . It's family but it's good . I'm glad you have all of that xxx .", ' so ‡ what kinds of things do you work on in speech ? Like reading , writing , talk ?'], 'id': [12, 13, 14, 15]}, {'predictions': [' um this one  uh this one or this one ‡ art  art oh okay „ oh cool art  ta uh drawing  drawing  drawing .', ' every time  drawing .', " and you're talking in your language .", ' okay ‡ stories . '], 'id': [16, 17, 18, 19]}, {'predictions': [' but  what can you do but really hard but family but really uh painful  b Billy and Craigs and  uh what can you do  awful . mhm yeah .', " uh could  hm could you tell me more about your family or maybe a trip that you've taken um with your family or for work ? You told me about all your traveling . Oh uh traveling ?", ' &//laughs right . ', " I don't know  . It's family but  okay ‡ interesting .  Drinking all the time , okay ‡ drinking .  But &//ges god all the time .  Promises , promises . But faith  but faith &//ges . "], 'id': [20, 21, 22, 23]}, {'predictions': [" all the time really but why but faith &//ges I don't know  I don't know faith yeah interesting . Do you go to church in Nashville now ? No way . No . Faith &//ges god all the time &//ges and this one  this one . ", ' oh okay jame you have the bible bible oh okay do you read it a lot really but uh this one okay oh I see okay so I see it has a morning prayer evening and evening', " okay so you do those you say them or you evening and every day it's a good practice yeah but it's good yeah and I see inspiration inspiration inspiration I don't know inspiration faith I don't know faith gotcha really spiritual  spiritual hm mhm .", ' Yeah ‡ so ‡ you were before your stroke also ?'], 'id': [24, 25, 26, 27]}, {'predictions': [' &//ges woohoo ‡ drinking okay and marijuana okay ‡ me  &//ges Tutingen Germany  Tutingen Germany  me okay ‡ Tutingen Germany  s okay  okay but sleeping ‡ two weeks coma but God &//ges . ', " I don't know  faith  healing  trying  I don't  okay  I don't really  okay  really interesting  healing  healing really I don't know  strange but interesting  treadmill  treadmill  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them  all of them ", ' the time . ', " I don't know why . I don't know why . But stupid . Really interesting . Faith . Why . Yeah but it's interesting . Yeah very . Yeah but it's good . It's good ."], 'id': [28, 29, 30, 31]}, {'predictions': [' no ‡ sometimes  yeah  yeah okay . ', " So next we're moving on .", ' go  yeah &//laughs yeah ‡ they tell a story . So I want you to tell me a story with a beginning , a middle , and an end about these pictures .', " sorry and  oh hurt and &//ges what's that &//ges ooh  ooh really &//ges pick that up &//ges mhm  mhm . Have you when you were little ? Yeah ‡ right . Little &//ges oh my god . Did you ever break ? Yes &//ges my god &//ges awful &//laughs ."], 'id': [32, 33, 34, 35]}, {'predictions': [' but hey this one  this one  uh this one  uh no  uh uh no  um uh no  uh &$%& dad  dad  dad all the time but  but old . ', ' but  old   dad   dad  awful but  old  but   but this one      soddy  one  this one  this one  . ', ' Our reception up here is so bad .', ' um  sari . '], 'id': [36, 37, 38, 39]}, {'predictions': [' your dad and your son is now old . No  no , but  no . Little but . When your son was little . No  no . ', ' This one  dad  your dad  dad yeah  Saudi  Saudi &-hm your dad yes is also named Saudi  Saudi gotcha but Venezuela  from Venezuela but this one', ' Baton Rouge . ', ' You did that ?'], 'id': [40, 41, 42, 43]}, {'predictions': [' really  uh fight  really  why really  uh really  mhm interesting . ', " the  ohmygod ‡ all the time .  Me and Tamra fight .  Money  money .  Me and Tamra fight all the time .  Money creates a lot of  you're right .  Yeah .", " what can you do survivor survivor yeah survivor okay so next there's some more pictures all right but also tell a story so if you could tell me a story again with a beginning middle and end about these pictures okay", " It's good , it's good . Relax . No , no . It's good . Hey , hot  &//ges . Raining . No , no . It's fine , it's fine . Oh my god . Oh ! Really oh my god . Raining . Oh shit ! Woohoo . Red . Wait . Raining . Oh . Stopping . Okay . Really ."], 'id': [44, 45, 46, 47]}, {'predictions': [" mhm  mhm it's good . Yep  yep that's exactly  yeah &//laughs could happen here . Yeah ‡ right mhm with these guys . Right &//ges oh ‡my god . Okay and this is our last picture . Woohoo ! So again just have a look all around . Oh cats  oh my god cats  cats and saving  oh cats !", ' oh my god um this one um oh my god uh driving oh my god um oh my god um driving oh my god um', ' ,  um dog  , um   um   man and  uh  r  sing  , br br um singing  rock and  singing  b l blogging . ', ' bird and racing policeman  and  and police um firemen  firemen and  firemen and  firemen and police .  Fut  flu  fut &-ges . '], 'id': [48, 49, 50, 51]}, {'predictions': [" Flutes  flutes  flutes  flutes  flutes  ohmygod .  Flutes  um okay . This ? Yeah ‡ right . It's a la . Ladder . Yeah ‡ ladder . Yeah ‡ yep . Ladder . It looks like they tried that once &//laughs . Poli  oh . Ladders .  Ladders . Yeah  yeah .", ' Were you starting to say rock and robin ?', " I'm I don't know really strange but rock and robin &//ges too too &-ges rock and robin &//ges too too too rock and robin &//ges ohmygod all the time . Interesting . Yeah . So next I'm gonna um have you tell another story . Okay . Another story . Have you heard of Cinderella ? Yeah ohmygod . Okay great so &//ges wow amazing .", ' Cinderella'], 'id': [52, 53, 54, 55]}, {'predictions': [" your own pace , take your time , and after  after  after you're done then tell me the story . Does that make sense ? Okay . Okay .", ' yeah ‡ sometimes it confuses me .', " it's when I first looked at it &//laughs .", ' Oh shit .'], 'id': [56, 57, 58, 59]}, {'predictions': [" I'm gonna do it a little lower . Lower ? Yeah ‡ there we go . It's on .", ' Mhm okay .', ' No ha ha here...', " okay okay all right great okay sorry you got it uhhuh I don't know mhm"], 'id': [60, 61, 62, 63]}, {'predictions': [' and just tell me as much of the story as you can . The story of Cinderella .', ' &//laughs and whoa !', ' &//ges', ' mhm .'], 'id': [64, 65, 66, 67]}, {'predictions': [' Oh this one .', " yeah ‡ but it's good yeah in end that was a great  that was a great version of Cinderella . I  I got a lot . Yeah ‡ but it's good &/. Great and it's good ? Uhhuh . It's good . Yeah . Do you like that story from the beginning ? It's  it's fine . Same ? Yeah . Yeah ‡ it's fine . Yeah . But girl &/. Mhm . Yes girl . But woman &/. Mhm . It's the same .", " the same yeah it's fine okay so we're gonna do something a little different okay but still talking okay um so okay water yes yes drink plenty &//laughs as she just grabbed her tea right  right  wa uh right &//laughs mhm I'll drink with you then &//laughs", ' uh this one .'], 'id': [68, 69, 70, 71]}, {'predictions': [' Try telling me first and then you can write next .', ' mhm .', " I haven't eaten them in a while yeah but it's really good but hey but it's really good mhm wow unbelievable it's fine it's fine mhm okay so we're done with the talking ohmygod so can  relax yes &-laughs but we are gonna do the test now okay test mhm but no more talking okay test &-laughs", ' okay so ‡ there is  this is a small table or for us or for you to be organized okay so okay okay ‡ what is happening in this picture ?'], 'id': [72, 73, 74, 75]}, {'predictions': [" this one  mhm  man and woman and  s swing um um swinging  mhm  swinging yeah  yeah alright and uh running and walking &-ges not running and  running and  s um &-woo I don't &- &- &- running and woo I don't know  r running and  s um &-", " trouble  trouble yeah ‡ trouble .  Does he look like his elbows going back ? Right  right . I see ya . Yeah . I don't know . Trouble . He looks like trouble . Yeah . Trouble . All right . So for these ones I'll say show me and then okay . Show me the lion . Lion .", ' Show me the drum . Drum  drum .', ' Show me the kite .'], 'id': [76, 77, 78, 79]}, {'predictions': [" uh &//laughs &-laughs and I'm too easy for you „ I'm sorry but &- okay &-laughs okay ‡ uh so next I'll  I'm gonna ask you some questions . Okay ‡ ask . Mhm and so you answer yes or no . Okay ‡ answer yes or no . Mhm . Yes or no ? Mhm . Yes or no ? Okay . You got it .", ' Yes . What ? No . No way . Axe ? No way . Really hurts . Yes .', " yes . If you're about to leave , have you left yet ? Okay . What  can you  yeah . If you're about to leave , have you left yet ? Okay . If you're about to leave , have you left yet ? No . I know . Tricky .", ' Yeah ‡ tricky &//ges whew . Are witnesses questioned by police ? Police ‡ yes . If I tell you I used to smoke , do you think I smoke now ? No . Are doctors treated by patients ? Yeah  patients „ yes . If I was at the park when you arrived , did I get there first ? First „ yes .'], 'id': [80, 81, 82, 83]}, {'predictions': [" If you're about to go upstairs , are you still downstairs ? Okay ‡ what ? If you're about to go upstairs , are you still downstairs ? No . Are cats chased by mice ? Mice ? No way ! Unless Tom and Jerry &-ges . Oh ‡ my god stupid . You're loving this . You're loving  I know this is all really exciting . Right ! Love it !", ' Oh my god love it .', ' Pants ?  What is this ? Ohmygod .  um &//ges.).) &-ges.).) &-ges.).) &-ges.).) chair . ', " um chairs but shit down um.).) I don't  yeah ‡ right ‡ I don't know . We were just talking &-ges I know . So our  okay ‡ it starts with we . Rea shit down  shit &-ges finger now &-mhm &-t tipping your tongue . Tongue yeah ‡ tongue ."], 'id': [84, 85, 86, 87]}, {'predictions': [" wheelchair  chair  wheelchair yeah  yeah I know you know it  you  you saw it in spade yeah  yeah okay ‡ what about this one ? I don't know &-laughs &-laughs &-laughs monster &-laughs &-laughs monster yeah  yeah monster but uh this one um um", ' flying  ocean  ocean  ocean  fla um ocean  dark  dark yeah', ' On a octopus . And okay this is the next one . What is that ?', ' . '], 'id': [88, 89, 90, 91]}, {'predictions': [" Swing  &//ges yeah ‡ it swings . It's light or it'll  it starts with  ha hammock . Yeah ‡ hammock . Yep ‡ you got it . Yeah ‡ hammock .", " I don't know but  &//ges yeah ‡ um it starts with s ? This one  s oh ‡ sorry it sounds with  the sound uh &//ges swing ? No um no ‡ no  no it  it starts with e and then s so it sounds like s s so s  s &//laughs", ' alright um .).)', ' S scare s temper . '], 'id': [92, 93, 94, 95]}, {'predictions': [" really take some more water oh my god okay uh so next um next I know there's more books yes okay so I want you to write on this line what this is so", " mask  &-mhm  I don't know  mask  &-ges oh  mask  mask  I don't know  mask  &-ges okay &-you s &-...", ' We can look later &//laughs .', ' why ohmygod  okay alright  mask   mask   mask   no no no no . '], 'id': [96, 97, 98, 99]}, {'predictions': [' Okay .', ' Mask. Mask.', ' so ‡ it starts with an m . m .', ' super close yeah that one there uh challenging me writing upside down not easy &//laughs alright but that was good once I gave you that first letter it  it clicked for you that was great okay yeah okay . '], 'id': [100, 101, 102, 103]}, {'predictions': [' well ‡ &-laughs made it 3D but &-laughs . Oh . Oh ‡ in this try and write a sentence if you can . But uh this one . Oh a tub ? Tub ? Mhm yeah .', " I don't know what is the boy doing rosh rosh okay wash tub mhm wash tub could you write what you're saying wash tub mhm wash oh", ' um scrub ?', ' yeah ‡ scrub and wash . Wash but no . Yeah .'], 'id': [104, 105, 106, 107]}, {'predictions': [' uh', ' uh.).) Pyramers  pyramers . ', " yeah ‡ you're close ‡ you got some of those letters „ it's ‡ pyramid , yeah &//laughs ah ‡ right and then it looks like you're kind of thinking of Egypt too , like that . Egypts , right , pharaohs , uhhuh , pharaohs , yep  yep , all very biblical as well . And it's good ? Yeah  yeah , you got it .", ' Kuulosti.'], 'id': [108, 109, 110, 111]}, {'predictions': [' Undetectable .', ' The sun rises in the east .', " The ambitious journalist discovered where we'd be going .", ' Show me the guitar.'], 'id': [112, 113, 114, 115]}, {'predictions': [' okay', " I feel fun is really good &-hm it's beautiful . Blues  blues . Oh blues music yeah . Have you been to Memphis ?", ' Show me the pear .', ' loud  mhm . Show me the chair . Chair ? Yeah . Okay . A couple more um questions where you say yes or no . Oh no . Mhm . Are you sitting ? Yes . Am I standing ? What ? Am I standing ? Yes . No no . Okay . Am I standing ?'], 'id': [116, 117, 118, 119]}, {'predictions': [" Yes okay mhm . Do you  I don't know , standing yes . Oh no  um &//laughs &-laughs I'd be really short . You're looking at my lip . No  no . Yeah ‡ you got it . You got it . Yeah I'm not  I'm not standing . No way no . We are both sitting . You got it . Yeah sitting . Yeah . Right sitting . Uhhuh . Do you eat ice cream with a spoon ?", ' hm yes yeah . ', " Yes  mhm  do you wear gloves on your feet ?  No  mhm  if you're about to go outside  are you still inside ? no  no way  mhm  are worms eaten by birds ?  &-laughs what  really  okay no  ohmygod  ohf &-gosh . ", " If I tell you I used to exercise , do you think I exercise now ? No ! Are babies delivered by doctors ? Yes . If you're about to start , have you started yet ? No . Are parents raised by children ? Yes ."], 'id': [120, 121, 122, 123]}, {'predictions': [' If you  last question if you were at the party when I arrived did you get there first ? What ? If you were at the party when I arrived did you get there first ? No ! Okay . Why ohmygod . I know . Ridiculous question .', ' okay awful  awful . ', " word you see . I don't know . Okay . Doh not . Okay . This one um okay . This one . ", ' I love that you do that in real life though . I wish I could  I wish you could do that now but  this one um'], 'id': [124, 125, 126, 127]}, {'predictions': [' Do you wanna try drawing it with your finger ? Have you practiced that before as a s dra ?', ' r no  s no um no &&& && no um very  no um s or j no um &&& && okay um protest  yeah protest .', ' um.).) pay  money  pay  money  pay &//. Credit card no  pay .).) um pay .).) uh', ' . '], 'id': [128, 129, 130, 131]}, {'predictions': [' & .) baby  uh baby  uh this one  uh this one  uh singing and  uh w singing and  whoa &-stop  stop and  sleeping &-oh this one  .', ' how are you and how are you ?', " How are you ? That was really good . But hey this one . Yes that is  I'll say it now . It's inexperienced . Experience . And this one . Proposition . Propo l proposition .", ' Thank you.'], 'id': [132, 133, 134, 135]}, {'predictions': [' music uh piano oh ‡ yeah  yeah okay ‡ so ‡ this word  show me which one is that word  which  which one  just one is that word what  okay can you  what  yeah so ‡ read  read &//ges uh and then  mhm and uh this one and uh this one .', ' this one um  um can I stop you for one second if you look at these pictures okay which  which one matches this word yeah ‡ right you got it you got it yeah okay yeah alright  oh ‡ thank you so much yeah alright yeah  yeah', ' ピタ you got it .', ' box . '], 'id': [136, 137, 138, 139]}, {'predictions': [" um you're really close if it was but you're really close because this first part that would be right so you got most of it right with that it says with that it says can with this it says cane um can oh really but yeah you got ninety percent of that word", ' yeah  yeah .', ' all these things just to see your mouth mhm . Mouth . Yeah . Okay . Next say ah . Ah .', ' Okay .'], 'id': [140, 141, 142, 143]}, {'predictions': [" we can keep going but yeah I  I just forgot &-laughs . Yes ! Thank you . You're welcome . Oh . It's cold . Woooo ! It's fancy . Wow . Thank you so much . A little bit in the light &-laughs . Mhm ! Wow . Unbelievable . Wow . Love it . Thank you so much . You are so such a favor &-laughs .", " It's good . Yeah , very sweet . Okay , uh  &//ges  bu bu bu bu bu bu bu bu bu bu bu bu bu uhhuh , and it's showing off again . It's so easy . Okay , so we're gonna add some sounds to that .", " you're close ‡ okay ‡ um you got it  you got it and then &q uh so &p uh tongue  &q &q &q &q okay so &pawdeca  pawdeca  pawdeca  pawdeca  pawdeca  pawdeca  ohmygod okay &-I know it's a mouth twister &q okay so &pawdeca  pawdeca", ' Yeah.'], 'id': [144, 145, 146, 147]}, {'predictions': [' &//ges mhm yeah alright and then just count to ten . one two three four five six seven eight  eight ten . one two three four five six seven eight nine ten . Yep! Ohmygod . Woohoo !'], 'id': [148]}]

In [ ]:
full_transcript = " ".join([" ".join(r["predictions"]) for r in sorted_results])
diarized_transcript = speaker_diarization(full_transcript)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1731"}/full_transcript.txt', 'w') as f:
  f.write(diarized_transcript)

In [ ]:
import csv

grammatical_features = get_grammatical_features(diarized_transcript, "*PAR")
lexical_features = get_lexical_features(diarized_transcript, dataset, "*PAR")
utterance_features = get_utterance_features(diarized_transcript, "*PAR")

all_features = grammatical_features | lexical_features | utterance_features
print(all_features)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1731"}/output_features.csv', 'w') as f:
  headers = list(all_features.keys())
  writer = csv.DictWriter(f, fieldnames=headers)

  writer.writeheader()
  writer.writerow(all_features)

{'%_nouns': 0.1050012440905698, '%_verbs': 0.06170689226175666, '%_adj': 0.009703906444389152, '%_adv': 0.012689723811893506, '%_PresP': 0.02139835780044787, '%_PastP': 0.001492908683752177, '%_Past': 0.01443145060960438, '%_aux': 0.02413535705399353, '%_mod': 0.002736999253545658, '%_pro': 0.02289126648420005, '%_3S': 0.005971634735008708, '%_prep': 0.02886290121920876, '%_conj': 0.03483453595421747, '%_det': 0.039313262005474, '%_plurals': 0.01567554117939786, 'noun_verb': 1.7016129032258065, 'open_closed': 0.19364419364419364, '#open-class': 652, '#closed-class': 3367, 'FREQ_types': 630, 'FREQ_tokens': 4019, 'FREQ_TTR': 0.1567554117939786, 'Words_Min': 53.98496171587733, 'total_utts': 404, 'mlu_utts': None, 'mlu_words': None}

# 1738

In [ ]:
dataset_output_path = f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1738"}/dataset.json'
dataset = load_dataset("json", data_files=dataset_output_path, field="data", split="train")

In [ ]:
results = []
for batch in dataset.batch(batch_size=4):
  audio_arrays = batch["audio"]
  features = feature_extractor(audio_arrays, sampling_rate=16000, return_tensors="pt").input_features.to(device)
  with torch.no_grad():
    prediction_ids = model.generate(inputs=features)
  predictions = tokenizer.batch_decode(prediction_ids, skip_special_tokens=True)
  results.append({"predictions": predictions, "id": batch["i"]})

sorted_results = sorted(results, key=lambda x: x["id"])
print(sorted_results)

[{'predictions': [' okay .', ' I can for the last seven and uh at times uh this tenth year I can wake up and feel fine and pronounce things very carefully .', ' uh yeah sure .', " uh behind my  uh a front of my uh doors and um I uh suddenly went uh I would say at this point I'll say blank but uh going back as far beyond this I couldn't get a hold myself and uh w I was uh"], 'id': [0, 1, 2, 3]}, {'predictions': [" It's  and the uh.).) house is very cold . It's very messy . And I sat for from some  between two and three days „ so ‡ wow ‡ okay .", ' Yeah  yeah . And so how has your uh recovery been since then and what kinds of things have you done to try to get better since your stroke ?', " I couldn't walk for about I think about four months  . Three or four months . But uh I'm uh have uh been doing the things I was asked to and uh and I read and I write and uh I draw and I walk w deal .", " Oh wow ‡ that's awesome . I love yoga too . I love yoga too ."], 'id': [4, 5, 6, 7]}, {'predictions': [" Yeah ‡ uh um well ‡ uh one on one therapy . Just sit down and um ‡ not exactly . It's more or less being connected to uh aphasia um of an um ‡", ' okay ‡ that makes sense .', " one because we really want to know more about your language okay uh so thinking back can you tell me a story about something important that happened to you in your life it could be happy or sad from any time and from when you were a kid or more recently just uh totally at random okay um anything important to you there's a so many different things are important to me I don't know", " I don't really want to draw from but uh um every week is uh I  experience um several things that are important really uh mind boggingly important so um okay ."], 'id': [8, 9, 10, 11]}, {'predictions': [" I'm currently uh I think I'm very concerned about uh the uh national political mood in this country and uh uh I'm uh working  um I'm um", ' Yeah  yeah yeah .', " as well so something like a trip you've taken or something about your family uh not too many trips lately i've been thinking about it a great deal i'm maybe hoping to return to california um if another maybe one to take .", " Two years so . I'm from California . Where ? Redondo beach . You know Media and Palos &Gges right near Long  uh Redondo beach yeah . I know PV ."], 'id': [12, 13, 14, 15]}, {'predictions': [" Yeah ‡ okay ‡ we'll go on to some uh picture descriptions . Okay . Okay ‡ so ‡ I'm gonna show you some pictures . By the way , Regina is one almost  almost my favorite beach almost long ago &-laughs . What is your favorite ?", " it okay so it's almost your favorite but you have three favorites so really it's like fourth place well it's it's second place oh okay okay I  I  d I have think about it it's long  it's long ago yeah I'm a big fan too okay wide  it used to be very wide I've  haven't been there for a while so yeah", " Yeah ‡ yeah there's  um yeah ‡ it's close to Hermosa , Manhattan , all those others too . I have a se first cousin living in  on the beach in man  Hermosa beach so ‡ oh yeah ‡ that's one of my favorites is Hermosa .", " They tell a story . So take a look at all of them and then I'll ask you to tell me the story with a beginning , a middle , and an end . And you can look at the pictures while you tell the story ."], 'id': [16, 17, 18, 19]}, {'predictions': [' So ‡ ‡ ‡', " Here are some more pictures that tell a story . Take a look at all of them and then again I'll ask for a story with a beginning , a middle and an end . And you can look at the pictures to tell the story .", " uh from the mother . Um he says goodbye , goes out and it starts raining . He runs back . Um it's all wet . The mother looks at him a bit um w scoldingly . So he takes the umbrella and he walks m to school .", ' I guess.'], 'id': [20, 21, 22, 23]}, {'predictions': [' or tell me a story about what you see . And again try make it a story with a beginning , middle and end .', " the kitty cat in the  in the branches . There's a ladder and a shifle and I see her . Um closer to the tree there's a full on looking man uh looking out as a b the kitty cat .", " The bar dog walks up at him and he too far and might are running with another ladder from the far truck to prissluny uh put the ladder up and rescue the man and um there's a bird sitting up and singing .", " and to the heavens . I'm really sorry . Yeah . You covered everything so &//laughs . I'm  was trying . Yeah &-laughs you were very thorough &-laughs . Close . Yeah &-laughs . Okay . So uh for this next part um um have you heard of the stories of Cinderella ? Yeah ."], 'id': [24, 25, 26, 27]}, {'predictions': [" Do you remember much about the story ? The basics yeah yeah . So what I'm gonna do is I have the picture book with no words in it um to let you uh take a look at the pictures and then I'll put the book away and have you tell me the story of Cinderella in your own words . Okay . So you can go ahead and look through all the pictures of the story .", " Go look first . Aha look first and then tell me when you're done with all of them .", " I'm not re going to remember that very well um .", ' Mhm .'], 'id': [28, 29, 30, 31]}, {'predictions': [" All right ‡ reach the end . I'm sorry . No ‡ it's okay . You ready ? Okay . So uh go ahead and tell me as much of the story of Cinderella as you can and just use any details you know about the story as well as the pictures you just looked at .", ' Cinderella was uh uh alarmingly pretty and uh good-natured and in the servitude of evil stepmother and two uh uh stepdaughters uh sepsisers and uh', " I really want the whole story right okay . I  I  I gotta keep awake but I'll try .  Uh so ‡ there's a ball . And the  uh mother and  the mother and the s s s are very worked up about the whole thing .", ' I gonna try on the best costumes .'], 'id': [32, 33, 34, 35]}, {'predictions': [" mother in sepersisco and  um and Cinderella is very forlorn but uh all the uh neighborhood um household careers are gathering  s send her off in a fancy gown and um I think she's seven .", ' .', ' .', ' the prince who is uh totally in over now and uh but uh the sti s cock strikes um ten and sorry uh w twelve and um she runs out the door uh and leaves with the prince .'], 'id': [36, 37, 38, 39]}, {'predictions': [' one shoe and the  and the  h and the  entres and um you get sick and carriage and rise home . ', " uh her godis's gown turns the old rags and he returns to the  to the hospital um s sorry the um day-to-day chores b and um this uh &-ges girl is uh her .", ' back and forth but uh the uh wicked stubborn and the s s s try to uh dress up and present themselves to the uh the uh princess uh emissaries and uh but uh', ' &//laughs yep &//laughs .'], 'id': [40, 41, 42, 43]}, {'predictions': [' Yeah!', " Yeah . Of course ‡ okay . Go on . No ‡ you can keep it . I'm sorry . I looked down and I didn't see . Okay . So ‡ the last part for this bit . Um so ‡ we're gonna do something a little bit different . I want you to tell me how you would make a peanut butter and jelly sandwich . I get um bread  I'm sorry . Wheat bread .", ' Yeah.', " gonna go back to  um to this . So we're done with all of the talking portions . Okay ."], 'id': [44, 45, 46, 47]}, {'predictions': [" Tell me what's happening in this picture . The  the two pictures . Yeah ‡ so ‡ we're gonna start with this one . Is uh the boy is uh pushing the  the girl in this one . Mhm . Great ‡ okay . So then what about this picture ? What's happening ?", " she looks happy and he's preceding the girl boy across the uh park or something . Great okay . Okay . So next gonna show you some pictures .", ' So uh show me the lion . Show me the drum . Drum . Show me the violin . Show me the giraffe . Okay . Next show me the bone .', " Show me the boot. And show me the goat. Okay. That's good. Yeah. Okay. So next I'm gonna ask you some questions and answer yes or no. Are you a man? Yeah. Am I a man? No. Do you cut the grass with an x?"], 'id': [48, 49, 50, 51]}, {'predictions': [" No. Are babies watched by babysitters? There's times. There's times? Okay. Do you open your door with a key? Um, most of the time, yes. If you're about to leave, have you left yet? No.", ' Yeah. No. No. Yeah.', ' Yeah. Are cats chased by mice ? Well ‡ no . Yeah . Although ‡ ‡ &-laughs &-a forget it . Spunky mice „ yeah . Believe me , as long as you  neither are  you are born yet , but go on . TomandJerry ? I know TomandJerry . No ‡ forget it . Okay &-laughs .', ' Okay .'], 'id': [52, 53, 54, 55]}, {'predictions': [" What about that ? uh an escalator . Mhm great ‡ okay . So for this next part um I'm gonna have you write . So um go ahead and write what that is on this line here .", ' Great ‡ and then that one . And then that one .', ' Okay and then what is happening in that one ?', ' Great ‡ okay . Thank you .'], 'id': [56, 57, 58, 59]}, {'predictions': [" after me house  house I'm sorry . House ? Oh  house . That's my fault &-laughs okay . I'm sorry  sorry  sorry . Um house ? Yes okay . Breakfast ? Breakfast . Catastrophe . Catastrophe . Undetectable .", " um the sun rises in the east the sun rises in the east this one's long &-laughs the ambitious journalist discovered where we'd be going the ambitious journalist discovered where we're going okay okay", ' Så...', " A pear? Show me the crown. Crown. Show me the cloud. Show me the chair. Great ‡ okay . Now I'm gonna ask you some more yes or no questions . Okay . Are you sitting right now ? Yeah ."], 'id': [60, 61, 62, 63]}, {'predictions': [' No. Yeah. No. No.', " I'm sorry. That's okay. Are worms eaten by birds ? Uh yeah . If I tell you I used to exercise , do you think I exercise now ? No . Are babies delivered by doctors ? Yeah . If you're about to start , have you started yet ? No .", ' raised by children .', " did you get there first ? If I'm on the party when you arrive I'm  got there first „ yes . Great job . Okay . So for this next part I'm gonna have you read some words out loud . So go ahead and just start with that one ."], 'id': [64, 65, 66, 67]}, {'predictions': [' Great. Okay . So next I want you to show me the picture that matches the word in the middle .', ' Mhm .', ' Yep ‡ alright .', ' So for this last part I want you to stick out your tongue and move it side to side as fast as you can . Okay um next I want you to say ah as long as you can hold it .'], 'id': [68, 69, 70, 71]}, {'predictions': [' Okei so next I want you to say pa um and over and over so pa pa pa pa as fast as you can .', ' And next catastrophe xxx .', " I believe that it's been the best test . Great . I'm looking back uh to the time that I have the MRI with you and I think actually it's uh maybe I'm a bit stronger overall . Good . That's awesome and I'm really glad to hear that .", " like rocks or progress so ‡ . Cool . I'm glad that's helping you . It sounds like the yoga and meditation and things like that or things ? I'm very picky about what yoga you do &//laughs . Yeah ‡ okay . So I'm  so I'm doing  do you go off in a side direction ? Just you  thank you &-laughs . It's something you could talk about for a while you're saying ?"], 'id': [72, 73, 74, 75]}, {'predictions': [' Yeah ‡ um ‡ briefly  briefly . Sure ‡ as much talking as we can get is great too &-laughs .', ' oh wow .', ' to me so ‡ yous look at me like I was a bit crazy &//laughs so ...'], 'id': [76, 77, 78]}]

In [ ]:
full_transcript = " ".join([" ".join(r["predictions"]) for r in sorted_results])
diarized_transcript = speaker_diarization(full_transcript)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1738"}/full_transcript.txt', 'w') as f:
  f.write(diarized_transcript)

In [ ]:
import csv

grammatical_features = get_grammatical_features(diarized_transcript, "*PAR")
lexical_features = get_lexical_features(diarized_transcript, dataset, "*PAR")
utterance_features = get_utterance_features(diarized_transcript, "*PAR")

all_features = grammatical_features | lexical_features | utterance_features
print(all_features)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1738"}/output_features.csv', 'w') as f:
  headers = list(all_features.keys())
  writer = csv.DictWriter(f, fieldnames=headers)

  writer.writeheader()
  writer.writerow(all_features)

{'%_nouns': 0.14285714285714285, '%_verbs': 0.11787072243346007, '%_adj': 0.021727322107550243, '%_adv': 0.011406844106463879, '%_PresP': 0.021184139054861488, '%_PastP': 0.010863661053775122, '%_Past': 0.035850081477457905, '%_aux': 0.042911461162411735, '%_mod': 0.005431830526887561, '%_pro': 0.06518196632265073, '%_3S': 0.018468223791417708, '%_prep': 0.06355241716458447, '%_conj': 0.049972840847365564, '%_det': 0.06735469853340575, '%_plurals': 0.019011406844106463, 'noun_verb': 1.2119815668202765, 'open_closed': 0.3254139668826494, '#open-class': 452, '#closed-class': 1389, 'FREQ_types': 508, 'FREQ_tokens': 1841, 'FREQ_TTR': 0.2759369907658881, 'Words_Min': 47.045187134359395, 'total_utts': 152, 'mlu_utts': None, 'mlu_words': None}

# 1833

In [ ]:
dataset_output_path = f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1833"}/dataset.json'
dataset = load_dataset("json", data_files=dataset_output_path, field="data", split="train")

In [ ]:
results = []
for batch in dataset.batch(batch_size=4):
  audio_arrays = batch["audio"]
  features = feature_extractor(audio_arrays, sampling_rate=16000, return_tensors="pt").input_features.to(device)
  with torch.no_grad():
    prediction_ids = model.generate(inputs=features)
  predictions = tokenizer.batch_decode(prediction_ids, skip_special_tokens=True)
  results.append({"predictions": predictions, "id": batch["i"]})

sorted_results = sorted(results, key=lambda x: x["id"])
print(sorted_results)

[{'predictions': [" So first .).) so ‡ first I'm just gonna be asking you to do some talking . So how do you think your speech is these days ? Not very good . That's  that's my take on it . How do you mean ? I can't think  I can't  .", ' hm hm', " that's okay .", ' Simple words .'], 'id': [0, 1, 2, 3]}, {'predictions': [" I won't be al able to spell it . But  uh but to think of it I can't . Mhm . So is it easier for you to think of the word to say it than to write it or it's about the same ? Uh even  um I sti still struggle to text . Mhm . Because I can't think of the w uh write uh .", " Spelling and  &//laughs and uh uh word phrase . Do you use speech to text ever ? Does that help or is it still &//ges ? The  uh uh she w gets aggravated &//laughs so I don't do that .", ' You had your stroke . Oh yeah . Um could you tell me about it ? Well  well ‡ the  the initial one um I remember um we always kiss before we uh go to bed and uh uh well sh she s said uh', " did bu a pucker it was just you know right here and uh um and I said um well well uh over and over again I could  I couldn't say just well &//laughs and  uh uh and I  I remember that uh the ride uh did pucker ."], 'id': [4, 5, 6, 7]}, {'predictions': [' Up to the uh gas station uh for the e.r. to Dova . I went  remember going in but that was the last thing I ever remember until I woke up in Vanderbilt . How did you get to Vanderbilt ? Uh ambulance . Mmhm . Uh what were your first memories afterwards ?', " I just  uh I was scared because uh I couldn't communicate and I had a deep depression so  and I had  hadta train all over again just to brush my teeth &//laughs so um", " but um your wife was saying that in terms of physical ability you've been good yeah since ?", ' Mhm yeah .'], 'id': [8, 9, 10, 11]}, {'predictions': [" uh if  we're in conversation right here and you know um the  um the  um I don't know you and right here I am sweating and I don't  I didn't  I didn't do that before the stroke .", ' Og uh &//laughs.).) så ‡.).) just to know &//ges that my  f my glasses fogged up &//ges and uh I  I &q am.).) starting to sweat &//laughs &//laughs . Oh no . &//laughs . Just with new people ? Yep . Hmm .', " a lengthy I  I start to s sweat too „ but uh &//laughs just like uh if I was going to Lowe's and I talk to the uh person you know uh I mean  whew &//laughs but I mean it's &//laughs just  just to  I think I'm  I was  embar I was  even I'm b uh I'm a little bit old .", " or uh to communicate because you know I stumble and  and uh can't think of the words and  and uh so every time I do that sweat get &//laughs so  but anyway &//laughs that's  it's so frustrating to me that you have to go through so much ."], 'id': [12, 13, 14, 15]}, {'predictions': [" and then the burden still feels like it's on you for having to express that . And I think hopefully now that there's a little bit more information um people can start to understand how to help communicate when people have been through something like what you've been through and to be more aware of it because it shouldn't be on you to have to feel embarrassed or anxious .", " because what you've done is amazing . But what you've done is amazing and to be as far as  to come as far as you have , to go from well well well to having a full conversation , I hope that's something that you still feel proud of , regardless of how difficult I'm sure it can be . I'm sorry to hear that . I can only imagine what that would feel like .", ' So ‡ kind of in that vein , how has your recovery been and what kinds of things have you been trying to do to improve since your stroke ? Well ‡ the uh speech therapist at Tenova . But uh that was  uh I think it was six months . Okay . So  but uh the insurance cut  cut me off .', ' Ha ha .'], 'id': [16, 17, 18, 19]}, {'predictions': [" uh was that  with the  with the writing ? Didn't you do that ? Did you work  oh okay . All the others  or  but brushing your teeth you said . Yeah okay . So only when you're in the hospital but not afterwards . Well it was still a challenge . Mhm . Even  even though uh got uh I  I don't know is it September I got home ? Mhm . Something like that .", ' So ‡ uh still had  hadta learn &//laughs all over again . Yeah ‡ so it sounds like mostly speech therapy after your stroke . What kinds of things did you do ?', " had  uh had me read and  uh and say  say the dumbest things over and over and over &//laughs . But  but I don't know uh just uh uh five youknow four  four words over and over again .", " and then five, four, I mean six, whatever . I've seen stuff like that before &//laughs . Was it with reading mostly or was it with talking too ? It was talking . She  she w she said it and then I said it . Well the  th that sentence and  and I hadta uh um &-"], 'id': [20, 21, 22, 23]}, {'predictions': [' Repeat .', " be happy it could be sad from a really long time ago when you were little or more recently anything important that's happened i don't know tell her how we knew you were having your stroke do what tell her how you were told you were having a heart attack oh we did  we did that one okay what about  how did you guys meet my  uh my dad was a preacher and she  uh not she he um", " went to uh Flint, Michigan from uh Florence, Alabama and uh uh in January of sixty seven and uh we're  uh sh uh he preached at uh uh her  her parents uh was converted and uh", " um so I  I s synked her out &//laughs but yeah . That's really sweet &-laughs . What about um when you got married ?"], 'id': [24, 25, 26, 27]}, {'predictions': [" in uh Henderson, Tennessee uh going to uh Freed-Harteman College and there was a college there then . It's not  now it's a university but um the  uh she was still in Flint, Michigan so that  had a long distance &-laughs relationship so then I  I started out preaching .", " &//ges and  um but  uh um but her dad was uh uh in General Motors and he was a um grinder of skill trades and uh he said that the shops were hiring but uh the shop he  uh the shops weren't hiring .", ' or as well as he  uh he thought &//laughs and uh we took  uh we  went o up there in January uh seventy three &//laughs and  uh and  uh and I get out in July uh thirty first um of seventy three so  .', ' But uh that was a good move because uh uh we had uh retirement and uh um the GeneralMotors stopped that uh retirement in probably o uh o seven or o eight and I retired in uh o three so  &-laughs .'], 'id': [28, 29, 30, 31]}, {'predictions': [" it was uh a good move &//laughs . It's good timing for you .", " benefits and uh so you coulda  I had  hadta uh hold down two jobs for benefits so uh I just  uh I decided not go along li those lines and I am thankful &-laughs so yeah  yeah I can imagine the security &-ges a lot nicer I'm sure .", ' Wow.', " Kate and um Blue Cross you know paid  paid huh ? Medicare and all . Yeah ‡ Medicare and Blue Cross paid for that &//laughs . Wow . I'm so glad that's  yeah ‡ I  I was really glad &-laughs him just  I can't imagine having to face a bill like that and having the uncertainty of how much would be covered &-so I'm glad that that was al &..."], 'id': [32, 33, 34, 35]}, {'predictions': [" significantly still not cheap but a lot cheaper than the face value . That's true . If I had  had a  be a preacher , he's gonna &//laughs . Yeah  yeah . But yeah ‡ grateful in that moment . That's right . Wow . Yeah ‡ I um yeah ‡ I can't imagine &-laughs I'm a student right now so knock on wood until I can get &//laughs .", " &-laughs you had a real job with some benefits and stuff too . Uh my glasses are fogging up . Oh okay . Well we can always take a break whenever you want and I hope I'm not making you nervous at all . I'm ma making myself nervous . Okay well just know you're doing great . I'm really enjoying getting to talk to you . There's no pressure . I know this is a test but it's not  it's really just listening to you talk so .", " Okay ‡ so ‡ for this next part I'm just gonna show you some pictures „ which  oh ‡ that's why you might need your glasses „ um they're pretty big but um so ‡ go ahead and take some time to look at them . Um they tell a story and so if you could tell me a story with a beginning , middle and end um and you can look at the pictures as you tell the story just whenever you're ready .", " So just kind of tell me what's happening essentially but a story just because  like a beginning , middle and end if you can . That's  yeah . Well the boy's kick  kicking the ball and then  and it goes through uh the uh window . And he lands on his father &-laughs and his father throws it back at him or &-laughs ."], 'id': [36, 37, 38, 39]}, {'predictions': [' or he gonna discipline him .', " so ‡ um again here's  the  these are some more pictures that tell a story just  um and so if you could again just a beginning  middle and end um tell me about what you see when you're ready . ", " uh uh don't want uh uh the umbrella . ", " Goes back and gets the  uh the umbrella so sh he could get dry or something . Yeah  yeah . Has it been raining out here a lot too the past few days ? Oh yes . Mhm . It's a lot warmer in Nashville today though than it is out here . We were surprised it was so cold . Really ? But not raining though . Okay ."], 'id': [40, 41, 42, 43]}, {'predictions': [" So this is the last picture. Good. But then there's more so we're not done. So again just go ahead and look at everything that's happening in this picture and then tell me the story with a beginning , middle and end um whenever you're ready.", " uh the cat and the dog chased him up the tree and dad uh got up on the tree and he lost his ladder and  uh and he's doesn't  probably doesn't need  afraid to the drop  uh get down and the fireman had it be called to get him .", ' The dad and the cat down .', " you to uh go ahead and flip through and remind you of how it goes and so you can go ahead and just go through all these pictures at your own pace and then I'll put the pictures away and after that um I'll have you tell me about the story ."], 'id': [44, 45, 46, 47]}, {'predictions': [' xxx .', ' Not a big fan of your book .', ' So now um tell me as much about the story of Cinderella as you can . You can use any details that you know about the story as well as anything that you saw in the pictures .', " Cinderella's um I don't know if it was mother or stepmother or anyway um two  uh two sisters or they're ugly and  uh and Cinderella's beautiful so  but they are ugly ."], 'id': [48, 49, 50, 51]}, {'predictions': [' into themselves and uh um the stepmother treats the other girls nice and uh um taking parties or  and Cinderella had the uh uh scrub the floors and um', ' and  um and  she was  uh stepmother was harsh and um so very good mother &//laughs comes in the view and uh helps her out and', ' turned a pumpkin into the chariot and uh um horses uh and any anyway animals turned into uh people and had glass slippers and  and uh she went to the ball and met the prince .', " and uh uh she had  she was late and the pumpkin uh turned out  turned back in and  and the horses uh and the men . So uh oh the prince uh tried to get the uh y younger's uh women to uh"], 'id': [52, 53, 54, 55]}, {'predictions': [' uh try on the slipper . And uh uh the uh two ugly s uh sisters uh um the  um the feet uh they  they tried to uh get  stick it in their feet .', ' to the slipper and  and uh so Cinderella um had  had a fit uh to the slipper and lived a happy li ever .', " yeah that's great all right this will be our last talking thing before we do um just the kind of evaluation you've done before the test you've done I think three times now yeah &-laughs in various forms so this is gonna be a little bit different tell me how you would make a peanut butter and jelly sandwich uh get red bread get the uh peanut butter and jelly sandwich .", " uh peanut butter and  jar and j uh jelly jar and uh get the knife and spread on the uh uh peanut butter and get a spoon and um dig out the uh jelly and  and the spoon is on the uh bread and  and you're done ."], 'id': [56, 57, 58, 59]}, {'predictions': [" I need it . Yeah ‡ sounds about right . I like your distinction between the knife for the peanut butter and the spoon for the jelly . I can tell that comes from a specific experience &-laughs . That's right &-laughs .", ' Okay.', " Yes. Do you take pictures with a camera? Yes. If you're about to finish , have you finished yet ? I guess &-laughs I don't know &-laughs . The  uh &-laughs .).) .", ' Yes. Yes. No.'], 'id': [60, 61, 62, 63]}, {'predictions': [' Tübyn . Yeah ‡ sure . If he was at the show when you arrived , did he get there first ? Yeah ‡ I think &//laughs . Are thieves robbed by victims ? No . If I tell you I used to drink coffee , do you think I drink coffee now ?', " If I tell you I used to drink coffee , do you think I drink coffee now ? Probably no &//laughs yeah ‡ that's great okay .", ' whatever you see here on that line there .', " I can't uh know how to spell it but  that's okay ‡ yeah ‡ it's a tricky one . I can't spell escalator . Okay , it's okay . Just do your best with whatever you  you can come up with and we  I can show you later also ."], 'id': [64, 65, 66, 67]}, {'predictions': [' And um that one if you can write  try to write a sentence if you can .', ' Yeah .', " It's a tricky one &-laughs okay so ‡ with this one I'm gonna have you repeat after me like that therapist had you repeat silly things I'm gonna have you repeat some silly things „ I apologize &-laughs okay so head head brother brother", " Proximity. Proximity. Inconceivable. Inconceivable. The baby drinks from a bottle. The baby drinks from the bottle. The confident vocalist realized where we'd be staying."], 'id': [68, 69, 70, 71]}, {'predictions': [" Just uh.).) that .).) no &//laughs no . I can try repeating it one more time . The confident vocalist realized where we'd be staying . The confident vocalist somewhere be staying anywhere .", ' Great okay .', ' Ja och då den...', " I'll have you just tell me what these things are . So ‡ what is this ? Bed . Mmhm . What is this ? Flower . Mushroom . Mmhm . Harmonica . Mmhm . Stork . Mmhm . Steth  stethoscope ."], 'id': [72, 73, 74, 75]}, {'predictions': [" Yeah that was great. Okay. So we did writing , did that . Okay more pictures . There's gonna be a lot of pictures in a row now . Okay so show me the lion .", " That's why I'm like that . Drum , yeah . Well ‡ mhm .", ' Show me the boot and show me the goat . Yeah . Okay . So , is it off of it ? Yeah . Cool . Thank you . Not a problem . Okay . So , a couple more yes no questions . Okay . Are you a man ? Yes . Am I a man ?', ' No. Yes. Yes. No. Yes.'], 'id': [76, 77, 78, 79]}, {'predictions': [' No. No. Yes. No.', ' Too sided question .', " raise the children but the children ends up raising the parents mhm yeah yep that's kind of how most people think about it usually so yeah alright they're reading out loud yeah mhm okay should I try and scroll the cover um for timing but oh I think it's okay okay", ' Go ahead and just read these out loud .'], 'id': [80, 81, 82, 83]}, {'predictions': [" That one's a weird one too so  &//laughs okay so next I'm gonna show you there's gonna be pictures and a word in the middle and then just show me the picture that matches the word in the middle.", ' zebra yeah .', ' sure mhm yeah', ' oh  okay .'], 'id': [84, 85, 86, 87]}, {'predictions': [" Ja seuraavaan um I'll have you say puh so ‡ and then just say it as quickly and as steadily as you can . So like puh puh puh puh puh .", " but as steadily as you can. So podica , podica , podica . Podica , podica , podica , podi anyway &//laughs podica  podica . Okay . Um so next could you do the same thing but with the word catastrophe ? Yeah ‡ right &//laughs . Yeah ‡ I know it's tricky .", " but it got catastrophe . Oh yeah ‡ well ‡ that's even harder . You're doing great with that . Just the word catastrophe . So like catastrophe  catastrophe .", ' Yeah ‡ got it . Okay and last just count to ten at a normal pace . One two three four five six seven eight nine ten .'], 'id': [88, 89, 90, 91]}, {'predictions': [" Wonderful ‡ that's great ‡ thank you  thank you ."], 'id': [92]}]

In [ ]:
full_transcript = " ".join([" ".join(r["predictions"]) for r in sorted_results])
diarized_transcript = speaker_diarization(full_transcript)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1833"}/full_transcript.txt', 'w') as f:
  f.write(diarized_transcript)

In [ ]:
import csv

grammatical_features = get_grammatical_features(diarized_transcript, "*PAR")
lexical_features = get_lexical_features(diarized_transcript, dataset, "*PAR")
utterance_features = get_utterance_features(diarized_transcript, "*PAR")

all_features = grammatical_features | lexical_features | utterance_features
print(all_features)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1833"}/output_features.csv', 'w') as f:
  headers = list(all_features.keys())
  writer = csv.DictWriter(f, fieldnames=headers)

  writer.writeheader()
  writer.writerow(all_features)

{'%_nouns': 0.15551743853630645, '%_verbs': 0.137221269296741, '%_adj': 0.04059462550028588, '%_adv': 0.022870211549456832, '%_PresP': 0.024013722126929673, '%_PastP': 0.010291595197255575, '%_Past': 0.07775871926815323, '%_aux': 0.05546026300743282, '%_mod': 0.008576329331046312, '%_pro': 0.08747855917667238, '%_3S': 0.036020583190394515, '%_prep': 0.07204116638078903, '%_conj': 0.09433962264150944, '%_det': 0.09491137793024586, '%_plurals': 0.030874785591766724, 'noun_verb': 1.1333333333333333, 'open_closed': 0.41276252019386106, '#open-class': 511, '#closed-class': 1238, 'FREQ_types': 440, 'FREQ_tokens': 1749, 'FREQ_TTR': 0.25157232704402516, 'Words_Min': 37.71437212187683, 'total_utts': 155, 'mlu_utts': None, 'mlu_words': None}

# 1944

In [ ]:
dataset_output_path = f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1944"}/dataset.json'
dataset = load_dataset("json", data_files=dataset_output_path, field="data", split="train")

In [ ]:
results = []
for batch in dataset.batch(batch_size=4):
  audio_arrays = batch["audio"]
  features = feature_extractor(audio_arrays, sampling_rate=16000, return_tensors="pt").input_features.to(device)
  with torch.no_grad():
    prediction_ids = model.generate(inputs=features)
  predictions = tokenizer.batch_decode(prediction_ids, skip_special_tokens=True)
  results.append({"predictions": predictions, "id": batch["i"]})

sorted_results = sorted(results, key=lambda x: x["id"])
print(sorted_results)

Batching examples:   0%|          | 0/114 [00:00<?, ? examples/s]

[{'predictions': [' Så først vil jeg spørre deg om du kan ta noen taler .', " and couldn't say anything . And then I went up and up &-and tu took therapy  speech therapy and went u and I got  got it back . And uh now I  but the second stroke I  I have  I have some times when I wanna say something and I can't say it .", " uh way away ‡ oh yeah ‡ I  I said it &//laughs youknow . So I hadta  hadta work on that „ hm yeah ‡ understandable . So ‡ I know you're tellin us a little bit earlier , but I didn't get to hear most of it . Um do you remember when you had your stroke ? I know you've had two you can talk about either .", " st I will  my first stroke I didn't  ha I didn't know what it was but I knew I was feelin.) you-know s uneasy and  and stuff and  and then I  r it  it came on me and uh on my second stroke I  I .) I  I figured it was uh another one ."], 'id': [0, 1, 2, 3]}, {'predictions': [' Og så um I knew.).) some other things I had.).) to go do . It was the same . So I .).) I  I  I  b I think I will say the second stroke because I .).) it was recent  youknow well recent uh than the first one .', ' Og så havde jeg det og went to uh uh the  uh went to a  h a hospital uh the one here .', ' The one that uh.).) it was.).) I  I want to say it . I  I stayed in the h hospital and I went to therapy . I went to speech and uh.).)', ' uh.).) I went to speech and I went to o.t and p.t yeah and uh.).) I went  I went to  fa to bathe myself  learn how to bathe myself and uh.).) um in o o.t I was  b'], 'id': [4, 5, 6, 7]}, {'predictions': [' um I would have some  uh some exercises to uh have it uh so I  w I could do my hand and s stuff and pt I learn how to walk .', ' yeah mhm mhm yeah . Lots of different therapies „ huh ? Yeah . But it sounds like they all were helping you a lot .', " I made a  what is it  the last five yeah . I had my  stro uh my p uh pt , speech and uh what is it  speech , o.t and p.t here . And I  I had  and it's very good and I had  that's what I say . I got all the way up .", ' and then I  I joined the  the  the  um what  um the thing &-laughs that I  wa the  I joined the &-ges you know what  you know I want  I  nu I want to say it . I joined it then .'], 'id': [8, 9, 10, 11]}, {'predictions': [" and I've been in there all the way . And I  I have been in there about  longer than anybody else . Oh yeah . Yeah . Um we had uh a banquet and I  I got uh a little plaque for that . Uh some  some people had died and stuff like that .", " the longest one there . But somebody  s other  b other people had joined  just joined or has had j more than other people . But I had more than all of them . Oh wow . Yeah &//laughs . And uh so you know and  and th that's  .", " I  I was very .).) I was very.).) proud of that &//laughs . Yeah ‡ that's an honor . That's really nice they gave you a plaque for it to show for all of your commitment to it .", " I need to join a book club myself . I need to get back into reading more . I'm gonna go ahead to thinking back . Can you tell me a story about something important that has happened to you in your life ? So it can be happy or sad . It can be from when you were younger or from more recently ."], 'id': [12, 13, 14, 15]}, {'predictions': [' Oh um... I had  what  I had my first a baby . It was a girl . And I  wa I  I  I had it and  and I  w I was very good  uh good  wa my  d I thought I have a  uh uh was a good mother and doing things for h her .', ' not such a little baby anymore .', " I woulda say you that  uh you that old ? And then I said I'm  I'm four  s I'm seventy one . I guess you are the  you know &-laughs . Do you have other kids too ? One . A  b a  a boy . He is uh th uh thirty . Yeah  yeah . All grown up . Yeah .", " Well ‡ next um can you check on your phone as well ? I'm sure it's good but I just wanted to  I don't like that I can't see it from over there . Yeah ‡ I'm sure that  ‡ can you say something else for us ? Oh ‡ I think it's  my son is forty &-laughs . Oh okay . Yeah &-laughs . It looks great . It looks good before I just  I normally keep an eye on it ."], 'id': [16, 17, 18, 19]}, {'predictions': [' Okei, thank you .', " soccer and he's playing ha happy and then he  se he  he  h he kicked the ball and the  the  w the window  the neighbor's window broke &-ges because he kicked it through the window and then the  the man what was sitting in the living and it  it was a soccer and it  it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccer and it was a soccerand it was a soccerand it was a soccerand it was a soccerand it was a soccerand it was a soccerand it was a soccerand it was a soccerand it was a soccerand it wasa the the  the  the man was sitting in the living room&Sso ‡ and it  the  the  the man was sitting in the living room&Sso ‡ and", " the  b the ball um came through and  and she  he was shocked &-laughs and the  the  the uh lamp f fell over and stuff and then he got up and he said it's a soccer ball and he looked out the window to see who k he kicked it &-laughs yeah &-laughs .", " Notice the lamp falling until you told me that . You're very observant . Oh yeah . Okay . So now I'm gonna show you some more pictures and they also tell a story . And again I'm gonna let you look at all of them and then tell me a story with a beginning , middle and end like you just did ."], 'id': [20, 21, 22, 23]}, {'predictions': [" oh this little  this little boy or a little girl . y y the  the uh you look like a  b uh you look like a b a girl . I don't know . But he's going to school and his mama is said .", " take this uh umbrella because it looks like rain and he said I don't wanna  I don't wanna take that I might l lose it or something it's not raining and  s and a as he goes to school it started to rain and it  r it rained and  ra and then he came back and he look  he was all wet and his mother said didn't I tell you that I'm a fast talker ?", " you to take the umbrella  . And so he got the umbrella and he started back to school . Have you ever had that happen with your kids too where they don't listen to you when you got it ? Oh no  no . If I tell them to take it they don't want to but they'll take it and then  and then they will  they will l lose it uh uh leave it at school &-laughs .", " I have one more picture for you . There's a lot going on in this picture . Go ahead and look at everything that's happening and then tell me a story about what you see and also with a beginning , middle and end if you can ."], 'id': [24, 25, 26, 27]}, {'predictions': [' uh uhhuh .', " at up and up  he  the cat is up in the tree . And so he said um please get my cat . And  um and she was riding on her  p her tricycle . And she ri tried to get the cat down , but he wouldn't go . And so he  he  he said up and up .", " he t uh uh asked the man to get it down with the ladder , but he didn't make it . He's still up in the tree , and the cat's up on the tree . And so they call the fire department , and  and  and the dog is uh barking for uh the man .", " they got the  c the cat out of the tree . A lot of stuff huh ? Yeah ‡ there  there is a lot . I didn't  I didn't mention the bird is just sitting there looking &//laughs . But she  she can  that's all she was gonna do &//laughs . Birds like this is my tree ? Yeah . You're all doing it ? Uhhuh ."], 'id': [28, 29, 30, 31]}, {'predictions': [' mhm .', ' Cinderella is  is this  um this is the  the front page uh in the story of  of Cinderella .', ' It good away and you can tell me just from your  in your own words .', ' okay .'], 'id': [32, 33, 34, 35]}, {'predictions': [' Mhm .', ' okay .', ' xxx .', ' .'], 'id': [36, 37, 38, 39]}, {'predictions': [" Allright ‡ I believe that's the last page . Double check . Yeah ‡ okay . Thank you .", ' from the pictures that you just looked at .', " girl and then  then his mother  his daddy said I'm going to marry this woman . She was uh a very treacherous woman and she  &-laughs and she wanted to marry him so he  they  ma they married and he  th she had two little girls .", " very  um very .).) very ugly girls &//laughs and  and so then the  the daddy died and oh she said she was gonna run the house and she didn't want  she didn't want"], 'id': [40, 41, 42, 43]}, {'predictions': [" uh Cinderella to have pretty clothes . She will  she wanted her to have rags and  and then she said , I don't have a  uh a um maid to run this house , so you will be the maid and you will one  pe be my  my maid  maid and the  the girls too .", ' and then by this time they had grown up and so she  ma she uh fixed the  st the  uh uh the  the  fixed the  um the  um the wood  the fire and did the housework and did the housework .', " and cook the d  b breakfast and stuff for them . Anything they wanted , she had to do it . And so she lip lived up in the attic . And  in  and when sh she had the animals to talk to her . The horse and the  the rats and  and the uh cat and things . That's all she had to talk to .", ' and uh uh uh telegram came because the king wants her his son to marry . So he had uh a ball , and so he  he told her , look and see who  who will you want to marry . But uh so um'], 'id': [44, 45, 46, 47]}, {'predictions': [' The  the two girls and  and the mother got some fancy clothes and everything to go to the  to the ball because she  she wanted  wanted them to marry their pants . So um the  mo the mother had left a dress for her and she  she said ,', " I will  I will use this  this  my mother's dress and I  I will uh fix it up . And then when  when the  uh the  the mother and the two girls uh one  uh had to get ready and dressed up and go to the ball .", " And Cinderella came down and say I wanna go too . And oh they was  they were very very ugly and say oh you wanna go ? You can't go . You can't . And I  I  she  ma she  ma uh uh the dress she had &-s they p pitted  she pitted out  they smashed it &-laughs .", " I didn't get that . And so after they had made the  uh dress  ma messy and torn , and they went to the  to the ball . And  and then s uh the  mo uh the mother put  uh um put s uh s uh Cinderella upstairs I think ."], 'id': [48, 49, 50, 51]}, {'predictions': [" Ups the  and so uh she couldn't go out and then uh the  the uh the fairy godmother came and Cinderella looked and she  and  and the mother se she told her they wouldn't let me go to the ball and so she went back .", " She said just a minute I'll see about this . And so um uh sh she got her a dress  a pretty dress and  and made the  the pumpkin and the rats and the  the cats and all . Made them the f uh footstove and  and the driver and thing and  and so you going to the ball .", " You must get back by twelve o'clock or all this I've fixed for you will  will be  um um be gone .  And so they all went to the ball and Cinderella came and the  the old  old  old m uh the old one .", ' um man the  o um the old  battle &//laughs was looking and the  and the girls were too . They say , who is that girl ? It was the girl in  going at the ball and looking  and look the  the pants is looking at her &//laughs .'], 'id': [52, 53, 54, 55]}, {'predictions': [" Og så... Og så dansede prinsen med henne hele natten . Og så hun ville vide  han ville vide, hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva' hva'", " s uh they were glass shoes and so  and uh the  the clock was  was chiming twelve o'clock so that she gotta  gotta let go because she said the  the fairy godmother said if you don't get ou out there by twelve you'll have all that stuff y y ube at home .", ' it  it  it will go back .  So she was going and running and running and she  one of the p s uh um shoes were left on  on the  the s uh s steps . And she was running and running because she would gotta get out of there . And the  the prince had a ', ' uh s somebody that looked after him . She was  come  come back  come back . We wanna  wanna see what  what your name is . But he  she ran and  &-laughs and then  then after twelve the all the  w went back . The pumpkin and  and the  the pumpkin .'], 'id': [56, 57, 58, 59]}, {'predictions': [' Rats and the  all the cats and the horse they all went back to what they were . And so then the  the  the um the prince said I gotta find that girl . Cause he  he loved her and he wanted to marry her .', " over the country , all over , and they  they couldn't find the girl . And so um s w uh the  the  uh old mother uh put her up in the  the  uh in the attic because they knew they was going all around for the show .", ' sjov . And so er  she  she looked &-ges they  um they  they came around her house and said ‡ I wanted you to look  look to you  to look at this shoe to see if you can wear it . And  &-laughs and  and uh b uh b uh', " uh oh girl  the big girl  the shoe is  is  it was  it didn't fit . It was  it was  this didn't fit . And the other one &-er said  she said I was  I was fitted , but it didn't fit either . And then the  s the  p the mice were saying downstairs is the prince ."], 'id': [60, 61, 62, 63]}, {'predictions': [" so ‡ you gotta get down there .  And so he  he  they  they opened the door . And so she ran down there and said here is  here's the other shoe . And the  and the  m and the mother and the girl look . What &//laughs ? She gotta  and so he  she got up .", ' She put her shoe on and the other shoe and they found it was her . And so they had a big wedding and they lived happy every after .', " uh you know I  I will  I  I was a teacher and I will tell all kind of stories &//laughs . Yeah ‡ I was gonna ask if you ever told your students or your kids the kind of stories you told ? Yeah  the kids and everything . Yeah  well ‡ I'm sure they loved it when you did . Oh yeah &//laughs .", " One more talking thing for you and then we're gonna do the language test and then just a couple more things and then we'll be  yeah okay . So this is gonna be a little bit different . I want you to tell me how you would make a peanut butter and jelly sandwich ."], 'id': [64, 65, 66, 67]}, {'predictions': [' um bed two pieces of a bed out of the  the  um out of the  um the bed is in the  um b the bed is in the  what is it  the bed is in the  um', " it's in the  s I say sack but that's not  the  the  the what  the thing that the beds stayed in &//laughs and so could  the peanut butter and the bed  the p two pieces of bed and the  uh the other one . ", ' okay you get p a piece of bread and you  oh you need a knife and then you  and then you put the peanut butter out of the jar and put it on the bed and you put another  the other piece on the  the top of the bed so you have two pieces of bed and a peanut butter .', " the butter and then you eat it . Yeah . Okay . Okay . Is this  uh is  is  this way I  s I think I  se  I say it &//laughs . Yeah . Okay . So next we're gonna do this test . Um and so for the first question ."], 'id': [68, 69, 70, 71]}, {'predictions': [' I would like you to tell me what is happening in that picture . Just that one .', " He's giving her a bubble bath . I guess that's his sister or this is his wife . One of the two . They're giving a bath to him . Great ! Yeah . And then what about this picture ?", ' um she is kicking him on the  s the  s uh knee . mhm . And uh yeah . Yep . Mhm . I forgot the pictures were different for a second . We have a couple versions of this and I had in my head a different picture . You did great . You described it right .', " So now I'm gonna show you some pictures and I'm gonna ask you to point to them when I say. Oh okay, alright. So show me the guitar. Is she? Show me the tiger. Show me the zebra. Yeah. Show me the saxophone. Mhm. Great okay. Mhm. Now some more of those."], 'id': [72, 73, 74, 75]}, {'predictions': [" So ‡ show me the pear . Show me the crown . Show me the cloud . And show me the chair . Great ‡ okay . Now I'm gonna ask you some yes-no questions . So answer yes or no . Yes or no .", " Yes. Am I standing ? No . Do you eat ice cream with a spoon ? Mmhm . Are spiders bitten by people ? No &//laughs . Do you wear gloves on your feet ? No &//laughs . If you're about to go outside , are you still inside ?", ' She goes out that  yeah  you inside  yeah . Are worms eaten by birds ? N no . Y wait a minute . Are worms eaten by bu birds ? Yeah &-laughs . If I tell you I used to exercise , do you think I exercise now ?', ' yeah .'], 'id': [76, 77, 78, 79]}, {'predictions': [" If you were at the party when I arrived , did you get there first ? Yeah . Great . Yeah ‡ but that parents and children question . Sometimes people say well &//laughs . Okay . So I'm gonna have you name some pictures now . Okay . So what is this ? A book .", ' Hva er dette om ?', ' He carries the babies .', " That's okay ‡ I know you know it um but we can move on if you would like . Does it help you if I say a sea ? uh a s .).) a sea .).) no  no . That's okay . It's a seahorse . Yep ."], 'id': [80, 81, 82, 83]}, {'predictions': [" Okay ‡ last one of these . What is that one ? That's  that's uh a pyramid here . Yeah  yeah . Okay . So um for this piece I'm gonna have you write next to it . Take your time . I know with your left hand it's harder . Okay . Um but so just write  what is that ? And you can just write it on that line there .", " That's a bed . And that ? A mushroom .", " I don't spell it right .", ' Step um  a  s step a scope . Oh boy .'], 'id': [84, 85, 86, 87]}, {'predictions': [' Det er alt jeg kan gjøre . Det er okay .', ' a girl pulling a boy in a wagon .', ' a girl pulling a boy . ', " And.).) a wagon &//ges there'll be.).) a.).) here's the .).) oh here  here ‡ no  no  no ‡ that's the  but it  it is the one that  it is  it's what it is &//laughs ."], 'id': [88, 89, 90, 91]}, {'predictions': [" loud when you're spelling ? Yeah mhm  mhm . Also I was just curious you were so close on this one . It's  I see you have for mushroom you have m u s s r o o m . Can you think of the letter that's missing with that one ? It's okay if you can't .", " There's an h there .", " Great okay um we'll go back . Okay so for this next part I'm gonna have you repeat after me . Okay . So man . Man . Blanket . Blanket . Prosperity . Prosperity . Insignificant . Oh insignificant . You got it &//laughs .", " The dog barks at the door . The  the dog bar

In [ ]:
full_transcript = " ".join([" ".join(r["predictions"]) for r in sorted_results])
diarized_transcript = speaker_diarization(full_transcript)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1944"}/full_transcript.txt', 'w') as f:
  f.write(diarized_transcript)

In [ ]:
import csv

grammatical_features = get_grammatical_features(diarized_transcript, "*PAR")
lexical_features = get_lexical_features(diarized_transcript, dataset, "*PAR")
utterance_features = get_utterance_features(diarized_transcript, "*PAR")

all_features = grammatical_features | lexical_features | utterance_features
print(all_features)

with open(f'drive/MyDrive/{APROCSA_DATASET_LOC}/{"1944"}/output_features.csv', 'w') as f:
  headers = list(all_features.keys())
  writer = csv.DictWriter(f, fieldnames=headers)

  writer.writeheader()
  writer.writerow(all_features)

{'%_nouns': 0.12839637719765584, '%_verbs': 0.09776238678742674, '%_adj': 0.018114011720831113, '%_adv': 0.014384656366542355, '%_PresP': 0.015982951518380393, '%_PastP': 0.008524240809802876, '%_Past': 0.038359083644112946, '%_aux': 0.04155567394778902, '%_mod': 0.005061267980820458, '%_pro': 0.05887053809270112, '%_3S': 0.020511454448588172, '%_prep': 0.03782631859350027, '%_conj': 0.05993606819392648, '%_det': 0.05966968566862014, '%_plurals': 0.018913159296750134, 'noun_verb': 1.3133514986376023, 'open_closed': 0.2691007437457742, '#open-class': 796, '#closed-class': 2958, 'FREQ_types': 537, 'FREQ_tokens': 3754, 'FREQ_TTR': 0.14304741608950453, 'Words_Min': 66.03904554169742, 'total_utts': 252, 'mlu_utts': None, 'mlu_words': None}

# End to end classification

## Utils

In [ ]:
overall_communication_impairment = {
    1738: 2,
    1944: 2,
    1713: 1,
    1554: 2,
    1833: 2,
    1731: 3
}

In [ ]:
import pandas as pd

In [ ]:
#@title Train data loading utils

def load_data():
  csv_path = f'drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/clan_features_with_labels.csv'
  return pd.read_csv(csv_path)

def train_and_test_participant_splits():
  random_participant_inds = np.random.choice(range(len(PARTICIPANT_NUMS)), size=2)
  test_participants = [int(PARTICIPANT_NUMS[i]) for i in random_participant_inds]
  train_participants = [int(PARTICIPANT_NUMS[i]) for i in range(len(PARTICIPANT_NUMS)) if i not in random_participant_inds]
  return (train_participants, test_participants)

EXTRACTED_FEATURES = ["%_Nouns", "%_Verbs", "%_adj", "%_adv",
        "%_PRESP", "%_PASTP", "%_PAST", "%_Aux", "%_Mod",
        "%_pro", "%_3S", "%_prep", "%_conj", "%_det",
        "%_Plurals", "noun_verb", "open_closed", "#open-class", "#closed-class",
        "FREQ_types", "FREQ_tokens", "FREQ_TTR", "Words_Min", "Total_Utts", "Overall communication impairment"]
CLAN_COLS = ["%_Nouns", "%_Verbs", "%_adj", "%_adv",
        "%_PRESP", "%_PASTP", "%_PAST", "%_Aux", "%_Mod",
        "%_pro", "%_3S", "%_prep", "%_conj", "%_det",
        "%_Plurals", "noun_verb", "open_closed", "#open-class", "#closed-class",
        "FREQ_types", "FREQ_tokens", "FREQ_TTR", "Words_Min", "Total_Utts"]
def filtered_train_dataset(df, train_participants):
  df = df[df["Participant"].isin(train_participants)]
  return df[EXTRACTED_FEATURES]

In [ ]:
#@title Test data loading utils
def load_test_data(test_participants):
  df = None
  for participant in test_participants:
    csv_path = f'drive/MyDrive/Stanford Classes/CS229/{APROCSA_DATASET_LOC}/{participant}/output_features.csv'
    dfi = pd.read_csv(csv_path)
    dfi["Participant"] = participant
    dfi["Overall communication impairment"] = overall_communication_impairment[participant]

    if df is None:
      df = dfi
    else:
      df = pd.concat([df, dfi])

  return df

COLUMN_ORDER = ["%_nouns", "%_verbs", "%_adj", "%_adv",
        "%_PresP", "%_PastP", "%_Past", "%_aux", "%_mod",
        "%_pro", "%_3S", "%_prep", "%_conj", "%_det",
        "%_plurals", "noun_verb", "open_closed", "#open-class", "#closed-class",
        "FREQ_types", "FREQ_tokens", "FREQ_TTR", "Words_Min", "total_utts"]
def filter_data_columns(df):
  return df[COLUMN_ORDER]

## Logistic Regression

In [ ]:
df = load_data()
train_participants, test_participants = train_and_test_participant_splits()
train_dataset = filtered_train_dataset(df, train_participants)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from scipy.sparse import hstack
import numpy as np

clan_X = df[CLAN_COLS].apply(pd.to_numeric, errors='coerce').fillna(0).values

scaler = StandardScaler()
X = scaler.fit_transform(clan_X)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

y = df["Overall communication impairment"].astype(int)

logreg = LogisticRegression(
    max_iter=2000,
    class_weight="balanced"  # important for small dataset
)

logreg.fit(X, y)

LogisticRegression(class_weight='balanced', max_iter=2000)

In [ ]:
test_data = load_test_data(test_participants)

y_test = test_data["Overall communication impairment"].astype(int)
print(y_test)

test_data = filter_data_columns(test_data)
X_test = scaler.transform(test_data)

preds = logreg.predict(test_data)
print(preds)
print("Accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))

0    2
0    2
Name: Overall communication impairment, dtype: int64
[2 2]
Accuracy: 1.0
              precision    recall  f1-score   support

           2       1.00      1.00      1.00         2

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

## XGBoost

In [ ]:
import pandas as pd
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from scipy.sparse import hstack
import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
df = load_data()
train_participants, test_participants = train_and_test_participant_splits()
train_data = filtered_train_dataset(df, train_participants)

test_data = load_test_data(test_participants)

y_test = test_data["Overall communication impairment"].astype(int)

test_data = filter_data_columns(test_data)

In [ ]:
# Prepare labels (convert to 0-indexed)
y_train = df["Overall communication impairment"].astype(int) - 1

# Extract features
exclude = ['Overall communication impairment']

train_clan_cols = [c for c in train_data.columns if c not in exclude]
test_clan_cols = [c for c in test_data.columns if c not in exclude]

# CLAN features
clan_X_train = train_data[train_clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values
clan_X_test = test_data[test_clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values

# Fit scaler on train only
scaler = StandardScaler()
clan_X_train_scaled = scaler.fit_transform(clan_X_train)
clan_X_test_scaled = scaler.transform(clan_X_test)

print(f"Dataset size: {len(df)} total")
print(f"Class distribution in test: {y.value_counts().sort_index().to_dict()}")

Dataset size: 54 total
Class distribution in test: {0: 9, 1: 36, 2: 9}

In [ ]:
# XGBoost model with heavy regularization
xgb = XGBClassifier(
    objective='multi:softprob',
    num_class=3,
    max_depth=2,
    n_estimators=30,
    learning_rate=0.05,
    min_child_weight=5,
    subsample=0.7,
    colsample_bytree=0.7,
    reg_alpha=1.0,
    reg_lambda=1.0,
    random_state=42
)
xgb.fit(clan_X_train_scaled, y_train)

XGBoostError: [03:55:19] /workspace/src/data/data.cc:557: Check failed: this->labels.Size() % this->num_row_ == 0 (18 vs. 0) : Incorrect size for labels: (54,1) v.s. 36
Stack trace:
  [bt] (0) /usr/local/lib/python3.12/dist-packages/xgboost/lib/libxgboost.so(+0x2bdf8c) [0x7e48a80bdf8c]
  [bt] (1) /usr/local/lib/python3.12/dist-packages/xgboost/lib/libxgboost.so(+0x5af3e0) [0x7e48a83af3e0]
  [bt] (2) /usr/local/lib/python3.12/dist-packages/xgboost/lib/libxgboost.so(+0x5b10b0) [0x7e48a83b10b0]
  [bt] (3) /usr/local/lib/python3.12/dist-packages/xgboost/lib/libxgboost.so(XGDMatrixSetInfoFromInterface+0x10b) [0x7e48a7fc7a4b]
  [bt] (4) /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e) [0x7e491da90e2e]
  [bt] (5) /lib/x86_64-linux-gnu/libffi.so.8(+0x4493) [0x7e491da8d493]
  [bt] (6) /usr/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x98c1) [0x7e491ecc78c1]
  [bt] (7) /usr/lib/python3.12/lib-dynload/_ctypes.cpython-312-x86_64-linux-gnu.so(+0x8ffe) [0x7e491ecc6ffe]
  [bt] (8) /usr/bin/python3(_PyObject_MakeTpCall+0x2fb) [0x53f5db]

In [ ]:
preds_xgb = xgb.predict(clan_X_test_scaled)
acc_xgb = accuracy_score(y_test, preds_xgb)
print(f"Test Accuracy: {acc_xgb:.3f}")
print(classification_report(y_test, preds_xgb))

ValueError: Feature shape mismatch, expected: 52, got 24

## Naive Bayes

In [ ]:
import pandas as pd
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, train_test_split, StratifiedKFold
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.metrics import accuracy_score, classification_report
from scipy.sparse import hstack
import numpy as np

In [ ]:
df = load_data()
train_participants, test_participants = train_and_test_participant_splits()
train_data = filtered_train_dataset(df, train_participants)

test_data = load_test_data(test_participants)

y_test = test_data["Overall communication impairment"].astype(int)

test_data = filter_data_columns(test_data)

In [ ]:
# Prepare features
exclude = ['Overall communication impairment']

clan_cols = [c for c in df.columns if c not in exclude]
y = df["Overall communication impairment"].astype(int) - 1

print(f"Total dataset size: {len(df)}")
print(f"Class distribution:\n{y.value_counts().sort_index()}\n")

Total dataset size: 54
Class distribution:
Overall communication impairment
0     9
1    36
2     9
Name: count, dtype: int64

In [ ]:
vectorizer = TfidfVectorizer(max_features=100, ngram_range=(1,2))
text_X_train = vectorizer.fit_transform(df_train["transcript_text"])
text_X_test = vectorizer.transform(df_test["transcript_text"])

nb_text = MultinomialNB()
nb_text.fit(text_X_train, y_train)
preds_text = nb_text.predict(text_X_test)

print(f"Test Accuracy: {accuracy_score(y_test, preds_text):.3f}")
print(f"\nClassification Report:")
print(classification_report(y_test, preds_text))

Test Accuracy: 0.636

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.64      1.00      0.78         7
           2       0.00      0.00      0.00         2

    accuracy                           0.64        11
   macro avg       0.21      0.33      0.26        11
weighted avg       0.40      0.64      0.49        11

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
clan_X_full = train_data[clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values
clan_X_full_scaled = StandardScaler().fit_transform(clan_X_full)

print("\n5-Fold CV Accuracy:")
cv_scores_clan = cross_val_score(
    GaussianNB(),
    clan_X_full_scaled,
    y,
    cv=5,
    scoring='accuracy'
)
print(f"Mean: {cv_scores_clan.mean():.3f} (+/- {cv_scores_clan.std():.3f})")
print(f"Individual folds: {cv_scores_clan}")

KeyError: "['File', 'Language', 'Corpus', 'Code', 'Age', 'Sex', 'Group', 'Role', 'Duration_(sec)', 'MLU_Utts', 'MLU_Words', 'MLU_Morphemes', 'Verbs_Utt', '%_Word_Errors', 'Utt_Errors', 'density', '%_13S', 'retracing', 'repetition', 'Participant', 'Word comprehension', 'Sentence comprehension', 'Word finding', 'Grammatical construction', 'Speech motor programming', 'Repetition', 'Reading', 'Overall'] not in index"

In [ ]:
X_train_combined = hstack([clan_X_train_scaled, text_X_train]).toarray()
X_test_combined = hstack([clan_X_test_scaled, text_X_test]).toarray()

nb_combined = GaussianNB()
nb_combined.fit(X_train_combined, y_train)
preds_combined = nb_combined.predict(X_test_combined)

print(f"Test Accuracy: {accuracy_score(y_test, preds_combined):.3f}")
print(f"\nClassification Report:")
print(classification_report(y_test, preds_combined))

Test Accuracy: 0.727

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.70      1.00      0.82         7
           2       1.00      0.50      0.67         2

    accuracy                           0.73        11
   macro avg       0.57      0.50      0.50        11
weighted avg       0.63      0.73      0.65        11

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# End to end classification 2

In [ ]:
EXTRACTED_FEATURES = ["%_Nouns", "%_Verbs", "%_adj", "%_adv",
        "%_PRESP", "%_PASTP", "%_PAST", "%_Aux", "%_Mod",
        "%_pro", "%_3S", "%_prep", "%_conj", "%_det",
        "%_Plurals", "noun_verb", "open_closed", "#open-class", "#closed-class",
        "FREQ_types", "FREQ_tokens", "FREQ_TTR", "Words_Min", "Total_Utts", "Overall communication impairment"]

In [ ]:
#@title Load dataset
import pandas as pd

csv_path = f'drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/clan_features_with_labels.csv'
df = pd.read_csv(csv_path)

df = df[EXTRACTED_FEATURES]

df.head()

,%_Nouns,%_Verbs,%_adj,%_adv,%_PRESP,%_PASTP,%_PAST,%_Aux,%_Mod,%_pro,...,noun_verb,open_closed,#open-class,#closed-class,FREQ_types,FREQ_tokens,FREQ_TTR,Words_Min,Total_Utts,Overall communication impairment
0,25.000,15.385,0.000,3.846,12.500,12.500,50.000,3.846,0.000,5.769,...,1.625,0.821,23,28,29,52,0.558,NaN,6,2.0
1,17.600,19.200,1.600,7.200,4.167,4.167,58.333,0.800,0.800,14.400,...,0.917,0.838,57,68,62,125,0.496,NaN,15,2.0
2,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,NaN,NaN,0,0,2,3,0.667,NaN,3,2.0
3,19.005,16.519,2.842,3.552,12.903,7.527,15.054,1.243,3.197,15.986,...,1.151,0.897,236,263,214,563,0.380,NaN,130,2.0
4,31.250,12.500,0.000,6.250,0.000,0.000,0.000,0.000,0.000,12.500,...,2.500,1.000,8,8,13,16,0.812,NaN,3,2.0

In [ ]:
#@title Baseline Logistic Regression

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from scipy.sparse import hstack
import numpy as np

exclude = [
    'File','Participant','Age','Sex','Group','Role',
    'Overall communication impairment','transcript_text'
]

clan_cols = [c for c in df.columns if c not in exclude]
clan_X = df[clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values

scaler = StandardScaler()
X = scaler.fit_transform(clan_X)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

y = df["Overall communication impairment"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

logreg = LogisticRegression(
    max_iter=2000,
    class_weight="balanced"  # important for small dataset
)

logreg.fit(X_train, y_train)

preds = logreg.predict(X_test)

print("Validation accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))

Validation accuracy: 0.6363636363636364
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         2
           2       0.67      0.86      0.75         7
           3       1.00      0.50      0.67         2

    accuracy                           0.64        11
   macro avg       0.56      0.45      0.47        11
weighted avg       0.61      0.64      0.60        11

In [ ]:
random_participant_inds = np.random.choice(range(len(PARTICIPANT_NUMS)), size=2)
test_participants = [int(PARTICIPANT_NUMS[i]) for i in random_participant_inds]
train_participants = [int(PARTICIPANT_NUMS[i]) for i in range(len(PARTICIPANT_NUMS)) if i not in random_participant_inds]

df = None
for participant in test_participants:
  csv_path = f'drive/MyDrive/Stanford Classes/CS229/{APROCSA_DATASET_LOC}/{participant}/output_features.csv'
  dfi = pd.read_csv(csv_path)
  dfi["Participant"] = participant
  dfi["Overall communication impairment"] = overall_communication_impairment[participant]

  if df is None:
    df = dfi
  else:
    df = pd.concat([df, dfi])

y_test = df["Overall communication impairment"].astype(int)
print(y_test)

COLUMN_ORDER = ["%_nouns", "%_verbs", "%_adj", "%_adv",
        "%_PresP", "%_PastP", "%_Past", "%_aux", "%_mod",
        "%_pro", "%_3S", "%_prep", "%_conj", "%_det",
        "%_plurals", "noun_verb", "open_closed", "#open-class", "#closed-class",
        "FREQ_types", "FREQ_tokens", "FREQ_TTR", "Words_Min", "total_utts"]
def filter_data_columns(df):
  return df[COLUMN_ORDER]

df = filter_data_columns(df)

df

0    2
0    2
Name: Overall communication impairment, dtype: int64

,%_nouns,%_verbs,%_adj,%_adv,%_PresP,%_PastP,%_Past,%_aux,%_mod,%_pro,...,%_plurals,noun_verb,open_closed,#open-class,#closed-class,FREQ_types,FREQ_tokens,FREQ_TTR,Words_Min,total_utts
0,0.142857,0.117871,0.021727,0.011407,0.021184,0.010864,0.035850,0.042911,0.005432,0.065182,...,0.019011,1.211982,0.325414,452,1389,508,1841,0.275937,47.045187,152
0,0.122355,0.090804,0.008465,0.016160,0.017314,0.006926,0.030396,0.034629,0.004617,0.053482,...,0.016545,1.347458,0.247720,516,2083,508,2599,0.195460,44.765568,246

In [ ]:
x_test = df.apply(pd.to_numeric, errors='coerce').fillna(0).values

preds = logreg.predict(scaler.transform(x_test))
print("Test accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))

Test accuracy: 1.0
              precision    recall  f1-score   support

           2       1.00      1.00      1.00         2

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

In [ ]:
#@title Baseline XG Boost

import pandas as pd
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from scipy.sparse import hstack
import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# Prepare labels (convert to 0-indexed)
y = df["Overall communication impairment"].astype(int) - 1

# Train/test split
train_idx, test_idx = train_test_split(
    df.index, test_size=0.2, stratify=y, random_state=42
)

df_train = df.loc[train_idx]
df_test = df.loc[test_idx]
y_train = y.loc[train_idx]
y_test = y.loc[test_idx]

# Extract features
exclude = [
    'File','Participant','Age','Sex','Group','Role',
    'Overall communication impairment','transcript_text'
]

clan_cols = [c for c in df.columns if c not in exclude]

# CLAN features
clan_X_train = df_train[clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values
clan_X_test = df_test[clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values

# Fit scaler on train only
scaler = StandardScaler()
X_train = scaler.fit_transform(clan_X_train)
X_test = scaler.transform(clan_X_test)

print(f"Dataset size: {len(df)} total, {len(train_idx)} train, {len(test_idx)} test")
print(f"Class distribution in test: {y_test.value_counts().sort_index().to_dict()}")

Dataset size: 54 total, 43 train, 11 test
Class distribution in test: {0: 2, 1: 7, 2: 2}

In [ ]:
# XGBoost model with heavy regularization
xgb = XGBClassifier(
    objective='multi:softprob',
    num_class=3,
    max_depth=2,
    n_estimators=30,
    learning_rate=0.05,
    min_child_weight=5,
    subsample=0.7,
    colsample_bytree=0.7,
    reg_alpha=1.0,
    reg_lambda=1.0,
    random_state=42
)
xgb.fit(X_train, y_train)
preds_xgb = xgb.predict(X_test)
acc_xgb = accuracy_score(y_test, preds_xgb)
print(f"Validation Accuracy: {acc_xgb:.3f}")
print(classification_report(y_test, preds_xgb))

Validation Accuracy: 0.636
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.64      1.00      0.78         7
           2       0.00      0.00      0.00         2

    accuracy                           0.64        11
   macro avg       0.21      0.33      0.26        11
weighted avg       0.40      0.64      0.49        11

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
random_participant_inds = np.random.choice(range(len(PARTICIPANT_NUMS)), size=2)
test_participants = [int(PARTICIPANT_NUMS[i]) for i in random_participant_inds]
train_participants = [int(PARTICIPANT_NUMS[i]) for i in range(len(PARTICIPANT_NUMS)) if i not in random_participant_inds]

df = None
for participant in test_participants:
  csv_path = f'drive/MyDrive/Stanford Classes/CS229/{APROCSA_DATASET_LOC}/{participant}/output_features.csv'
  dfi = pd.read_csv(csv_path)
  dfi["Participant"] = participant
  dfi["Overall communication impairment"] = overall_communication_impairment[participant]

  if df is None:
    df = dfi
  else:
    df = pd.concat([df, dfi])

y_test = df["Overall communication impairment"].astype(int)
print(y_test)

COLUMN_ORDER = ["%_nouns", "%_verbs", "%_adj", "%_adv",
        "%_PresP", "%_PastP", "%_Past", "%_aux", "%_mod",
        "%_pro", "%_3S", "%_prep", "%_conj", "%_det",
        "%_plurals", "noun_verb", "open_closed", "#open-class", "#closed-class",
        "FREQ_types", "FREQ_tokens", "FREQ_TTR", "Words_Min", "total_utts"]
def filter_data_columns(df):
  return df[COLUMN_ORDER]

df = filter_data_columns(df)

df

0    2
0    1
Name: Overall communication impairment, dtype: int64

,%_nouns,%_verbs,%_adj,%_adv,%_PresP,%_PastP,%_Past,%_aux,%_mod,%_pro,...,%_plurals,noun_verb,open_closed,#open-class,#closed-class,FREQ_types,FREQ_tokens,FREQ_TTR,Words_Min,total_utts
0,0.128396,0.097762,0.018114,0.014385,0.015983,0.008524,0.038359,0.041556,0.005061,0.058871,...,0.018913,1.313351,0.269101,796,2958,537,3754,0.143047,66.039046,252
0,0.100636,0.086864,0.008475,0.020657,0.011123,0.003708,0.043962,0.039195,0.005297,0.069915,...,0.019597,1.158537,0.207933,325,1563,447,1888,0.236758,52.081331,171

In [ ]:
x_test = scaler.transform(df)
preds_xgb = xgb.predict(x_test)
acc_xgb = accuracy_score(y_test, preds_xgb)
print(f"Test Accuracy: {acc_xgb:.3f}")
print(classification_report(y_test, preds_xgb))

Test Accuracy: 0.500
              precision    recall  f1-score   support

           1       0.50      1.00      0.67         1
           2       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
#@title Baseline Naive Bayes

In [ ]:
transcripts = {}
for participant in PARTICIPANT_NUMS:
  transcript = ""
  with open(f'drive/MyDrive/Stanford Classes/CS229/cs229_final_proj/aprocsa_dataset/{participant}/full_transcript.txt', 'r') as f:
    transcript = f.read()
  transcripts[int(participant)] = transcript

In [ ]:
import pandas as pd
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, train_test_split, StratifiedKFold
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.metrics import accuracy_score, classification_report
from scipy.sparse import hstack
import numpy as np

In [ ]:
# Prepare features
exclude = [
    'File','Participant','Age','Sex','Group','Role',
    'Overall communication impairment','transcript_text'
]

clan_cols = [c for c in df.columns if c not in exclude]
y = df["Overall communication impairment"].astype(int) - 1

print(f"Total dataset size: {len(df)}")
print(f"Class distribution:\n{y.value_counts().sort_index()}\n")

# Split data
train_idx, test_idx = train_test_split(
    df.index, test_size=0.2, stratify=y, random_state=42
)

df_train = df.loc[train_idx]
df_test = df.loc[test_idx]
y_train = y.loc[train_idx]
y_test = y.loc[test_idx]

Total dataset size: 54
Class distribution:
Overall communication impairment
0     9
1    36
2     9
Name: count, dtype: int64

In [ ]:
random_participant_inds = np.random.choice(range(len(PARTICIPANT_NUMS)), size=2)
test_participants = [int(PARTICIPANT_NUMS[i]) for i in random_participant_inds]
train_participants = [int(PARTICIPANT_NUMS[i]) for i in range(len(PARTICIPANT_NUMS)) if i not in random_participant_inds]

train_text_data = [transcripts[p] for p in train_participants]
test_text_data = [transcripts[p] for p in test_participants]

In [ ]:

vectorizer = TfidfVectorizer(max_features=100, ngram_range=(1,2))
text_X_train = vectorizer.fit_transform(train_text_data)
text_X_test = vectorizer.transform(test_text_data)

y_train = [overall_communication_impairment[i] for i in train_participants]
y_test = [overall_communication_impairment[i] for i in test_participants]

nb_text = MultinomialNB()
nb_text.fit(text_X_train, y_train)
preds_text = nb_text.predict(text_X_test)

print(f"Test Accuracy: {accuracy_score(y_test, preds_text):.3f}")
print(f"\nClassification Report:")
print(classification_report(y_test, preds_text))

Test Accuracy: 0.000

Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       2.0
           2       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
clan_X_full = df[clan_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values
clan_X_full_scaled = StandardScaler().fit_transform(clan_X_full)

print("\n5-Fold CV Accuracy:")
cv_scores_clan = cross_val_score(
    GaussianNB(),
    clan_X_full_scaled,
    y,
    cv=5,
    scoring='accuracy'
)
print(f"Mean: {cv_scores_clan.mean():.3f} (+/- {cv_scores_clan.std():.3f})")
print(f"Individual folds: {cv_scores_clan}")

5-Fold CV Accuracy:
Mean: 0.515 (+/- 0.161)
Individual folds: [0.36363636 0.63636364 0.72727273 0.54545455 0.3       ]

In [ ]:
X_train_combined = hstack([clan_X_train_scaled, text_X_train]).toarray()
X_test_combined = hstack([clan_X_test_scaled, text_X_test]).toarray()

nb_combined = GaussianNB()
nb_combined.fit(X_train_combined, y_train)
preds_combined = nb_combined.predict(X_test_combined)

print(f"Test Accuracy: {accuracy_score(y_test, preds_combined):.3f}")
print(f"\nClassification Report:")
print(classification_report(y_test, preds_combined))

NameError: name 'clan_X_train_scaled' is not defined